## Uploading data and basic operations (add season variable and change the date format)

In [1]:
import numpy as np
import pandas as pd

In [2]:
league_code = 'SP1'
seasons = ["00-01", "01-02", "02-03", "03-04", "04-05", 
          "05-06", "06-07", "07-08", "08-09", "09-10", 
          "10-11", "11-12", "12-13", "13-14", "14-15", 
          "15-16", "16-17", "17-18", "18-19", "19-20", "20-21"]

In [3]:
urls = []
for season in seasons:
    x = 'https://www.football-data.co.uk/mmz4281/' + season.replace("-", "") + '/'+league_code + '.csv'
    urls.append(x)

In [4]:
columns = ['Div', 'Date','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS', 'HST', 'AST', 'B365H', 'B365D', 'B365A']

I want to focus on the last 10 completed seasons (from 2011/12 to 2020/21) but i need more historical data to calculate H2H (Head To Head) variables

In some data from historical season there was no columns with shots data so I decided to also cut shots data from 00/01 to 10/11 season

In [5]:
LaLiga_00_01_data = pd.read_csv(urls[0])[columns[0:-7]]
LaLiga_01_02_data = pd.read_csv(urls[1])[columns[0:-7]]
LaLiga_02_03_data = pd.read_csv(urls[2])[columns[0:-7]]
LaLiga_03_04_data = pd.read_csv(urls[3])[columns[0:-7]]
LaLiga_04_05_data = pd.read_csv("match_data/SP1_04_05.csv", sep=';', encoding= 'unicode_escape')[columns[0:-7]] # Error Tokenizing Data with urls upload
LaLiga_05_06_data = pd.read_csv(urls[5])[columns[0:-7]]
LaLiga_06_07_data = pd.read_csv(urls[6])[columns[0:-7]]
LaLiga_07_08_data = pd.read_csv(urls[7])[columns[0:-7]]
LaLiga_08_09_data = pd.read_csv(urls[8])[columns[0:-7]]
LaLiga_09_10_data = pd.read_csv(urls[9])[columns[0:-7]]
LaLiga_10_11_data = pd.read_csv(urls[10])[columns[0:-7]]
LaLiga_11_12_data = pd.read_csv(urls[11])[columns]
LaLiga_12_13_data = pd.read_csv(urls[12])[columns]
LaLiga_13_14_data = pd.read_csv(urls[13])[columns]
LaLiga_14_15_data = pd.read_csv(urls[14])[columns]
LaLiga_15_16_data = pd.read_csv(urls[15])[columns]
LaLiga_16_17_data = pd.read_csv(urls[16])[columns]
LaLiga_17_18_data = pd.read_csv(urls[17])[columns]
LaLiga_18_19_data = pd.read_csv(urls[18])[columns]
LaLiga_19_20_data = pd.read_csv(urls[19])[columns]
LaLiga_20_21_data = pd.read_csv(urls[20])[columns]

In [6]:
LaLiga_20_21_data['Season'] = '2020/21'
LaLiga_19_20_data['Season'] = '2019/20'
LaLiga_18_19_data['Season'] = '2018/19'
LaLiga_17_18_data['Season'] = '2017/18'
LaLiga_16_17_data['Season'] = '2016/17'
LaLiga_15_16_data['Season'] = '2015/16'
LaLiga_14_15_data['Season'] = '2014/15'
LaLiga_13_14_data['Season'] = '2013/14'
LaLiga_12_13_data['Season'] = '2012/13'
LaLiga_11_12_data['Season'] = '2011/12'
LaLiga_10_11_data['Season'] = '2010/11'
LaLiga_09_10_data['Season'] = '2009/10'
LaLiga_08_09_data['Season'] = '2008/09'
LaLiga_07_08_data['Season'] = '2007/08'
LaLiga_06_07_data['Season'] = '2006/07'
LaLiga_05_06_data['Season'] = '2005/06'
LaLiga_04_05_data['Season'] = '2004/05'
LaLiga_03_04_data['Season'] = '2003/04'
LaLiga_02_03_data['Season'] = '2002/03'
LaLiga_01_02_data['Season'] = '2001/02'
LaLiga_00_01_data['Season'] = '2000/01'

In [7]:
seasons = [LaLiga_00_01_data, LaLiga_01_02_data, LaLiga_02_03_data, LaLiga_03_04_data, LaLiga_04_05_data,
          LaLiga_05_06_data, LaLiga_06_07_data, LaLiga_07_08_data, LaLiga_08_09_data, LaLiga_09_10_data, 
          LaLiga_10_11_data, LaLiga_11_12_data, LaLiga_12_13_data, LaLiga_13_14_data, LaLiga_14_15_data, 
          LaLiga_15_16_data, LaLiga_16_17_data, LaLiga_17_18_data, LaLiga_18_19_data, LaLiga_19_20_data, 
          LaLiga_20_21_data]

In [8]:
# checking if every season was uploaded correctly without NA
for season in seasons:
    print(season.Season.unique())
    print(season.Date[0])
    print(len(season)) # every season should have 380 rows
    print('|----------------------------|')

['2000/01']
09/09/00
380
|----------------------------|
['2001/02']
25/08/01
380
|----------------------------|
['2002/03']
31/08/02
380
|----------------------------|
['2003/04']
30/08/03
380
|----------------------------|
['2004/05']
28.08.2004
380
|----------------------------|
['2005/06']
27/08/05
380
|----------------------------|
['2006/07']
26/08/06
380
|----------------------------|
['2007/08']
25/08/07
380
|----------------------------|
['2008/09']
30/08/08
380
|----------------------------|
['2009/10']
29/08/09
380
|----------------------------|
['2010/11']
28/08/10
380
|----------------------------|
['2011/12']
27/08/11
380
|----------------------------|
['2012/13']
18/08/12
380
|----------------------------|
['2013/14']
17/08/13
380
|----------------------------|
['2014/15']
23/08/14
380
|----------------------------|
['2015/16']
21/08/15
380
|----------------------------|
['2016/17']
19/08/16
380
|----------------------------|
['2017/18']
18/08/17
380
|----------------------------|
['2018/19']
17/08/2018
380
|----------------------------|
['2019/20']
16/08/2019
380
|----------------------------|
['2020/21']
12/09/2020
380
|----------------------------|

In [9]:
# changing Date format
for season in seasons:
    season.Date = pd.to_datetime(season.Date, dayfirst=True)

## Adds the number of games played by the team before specific match

In [10]:
def get_last_matches_number(playing_stat):
    
    # Diffrent lists for HomeTeam and AwayTeam because sometimes number of games played before 
    # can be diffrent becasue of postponing the match
    HT_Match_number = []
    AT_Match_number = []
    
    # dataset iteration over each row
    for i, row in playing_stat.iterrows():
        df_nad = playing_stat.iloc[0:i]
        df_specific_match = playing_stat.iloc[i]

        ht = df_specific_match.HomeTeam
        at = df_specific_match.AwayTeam

        x = len(df_nad[(df_nad.HomeTeam == ht) | (df_nad.AwayTeam == ht)])
        y = len(df_nad[(df_nad.HomeTeam == at) | (df_nad.AwayTeam == at)])

        HT_Match_number.append(x)
        AT_Match_number.append(y)
        
    playing_stat['HT_last_matches_number'] = HT_Match_number
    playing_stat['AT_last_matches_number'] = AT_Match_number
    
    return playing_stat

In [11]:
for season in seasons:
    season = get_last_matches_number(season)

## Goals scored and conceded before specific match

In [12]:
# Gets the goals scored aggregation arranged by teams and matchweek
def get_goals_scored(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        HTGS = playing_stat.iloc[i]['FTHG']
        ATGS = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGS)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGS)
        
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsScored = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    GoalsScored[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39): # we have 38 matchweeks (number of teams*2 - 2 becacue you cant play with yourself)
        GoalsScored[i] = GoalsScored[i] + GoalsScored[i-1]
    return GoalsScored

# Gets the goals conceded aggregation arranged by teams and matchweek
def get_goals_conceded(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        ATGC = playing_stat.iloc[i]['FTHG']
        HTGC = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGC)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    GoalsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        GoalsConceded[i] = GoalsConceded[i] + GoalsConceded[i-1]
    return GoalsConceded

# function summarizing and adding variables
def get_gss(playing_stat):
    GC = get_goals_conceded(playing_stat)
    GS = get_goals_scored(playing_stat)
   
    HTGS = []
    ATGS = []
    HTGC = []
    ATGC = []
    
    for i in range(len(playing_stat)):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam

        ht_match = playing_stat.iloc[i].HT_last_matches_number
        at_match = playing_stat.iloc[i].AT_last_matches_number

        HTGS.append(GS.loc[ht][ht_match])
        ATGS.append(GS.loc[at][at_match])
        
        HTGC.append(GC.loc[ht][ht_match])
        ATGC.append(GC.loc[at][at_match])
        
        
    playing_stat['HTGS'] = HTGS
    playing_stat['ATGS'] = ATGS
    playing_stat['HTGC'] = HTGC
    playing_stat['ATGC'] = ATGC
    
    return playing_stat

In [13]:
for season in seasons:
    season = get_gss(season)

## Shots on target took and allowed before specific match

In [14]:
# Gets the shots on target took aggregation arranged by teams and matchweek
def get_shots_on_target_took(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        HTSOT = playing_stat.iloc[i]['HST']
        ATSOT = playing_stat.iloc[i]['AST']
        teams[playing_stat.iloc[i].HomeTeam].append(HTSOT)
        teams[playing_stat.iloc[i].AwayTeam].append(ATSOT)
        
    # Create a dataframe for shots on target took where rows are teams and cols are matchweek.
    ShotsOT = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    ShotsOT[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        ShotsOT[i] = ShotsOT[i] + ShotsOT[i-1]
    return ShotsOT

# Gets the shots on target allowed aggregation arranged by teams and matchweek
def get_shots_on_target_allowed(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        ATSOT_A = playing_stat.iloc[i]['HST']
        HTSOT_A = playing_stat.iloc[i]['AST']
        teams[playing_stat.iloc[i].HomeTeam].append(HTSOT_A)
        teams[playing_stat.iloc[i].AwayTeam].append(ATSOT_A)
    
    # Create a dataframe for shots on target allowed where rows are teams and cols are matchweek.
    ShotsOT_Allowed = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    ShotsOT_Allowed[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        ShotsOT_Allowed[i] = ShotsOT_Allowed[i] + ShotsOT_Allowed[i-1]
    return ShotsOT_Allowed

# function summarizing and adding variables
def get_sot(playing_stat):
    SOT_T = get_shots_on_target_took(playing_stat)
    SOT_A = get_shots_on_target_allowed(playing_stat)
   
    HTSOT_T = []
    ATSOT_T = []
    HTSOT_A = []
    ATSOT_A = []
    
    for i in range(len(playing_stat)):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam

        ht_match = playing_stat.iloc[i].HT_last_matches_number
        at_match = playing_stat.iloc[i].AT_last_matches_number

        HTSOT_T.append(SOT_T.loc[ht][ht_match])
        ATSOT_T.append(SOT_T.loc[at][at_match])
        
        HTSOT_A.append(SOT_A.loc[ht][ht_match])
        ATSOT_A.append(SOT_A.loc[at][at_match])
        
        
    playing_stat['HTSOT_T'] = HTSOT_T
    playing_stat['ATSOT_T'] = ATSOT_T
    playing_stat['HTSOT_A'] = HTSOT_A
    playing_stat['ATSOT_A'] = ATSOT_A
    
    return playing_stat

In [15]:
for season in [ LaLiga_11_12_data,
            LaLiga_12_13_data, 
            LaLiga_13_14_data,
            LaLiga_14_15_data, 
            LaLiga_15_16_data, 
            LaLiga_16_17_data, 
            LaLiga_17_18_data, 
            LaLiga_18_19_data, 
            LaLiga_19_20_data, 
            LaLiga_20_21_data]:
    season = get_sot(season)

In [16]:
# Get shots accuracy
def get_shots_acc(playing_stat):
    
    HT_Shot_Acc = playing_stat.HTGS / playing_stat.HTSOT_T # HomeTeam shots took accuracy (Goals scoring accuracy)
    AT_Shot_Acc = playing_stat.ATGS / playing_stat.ATSOT_T # AwayTeam shots took accuracy (Goals scoring accuracy)
    
    HT_Op_Shot_Acc = playing_stat.HTGC / playing_stat.HTSOT_A # HomeTeam shots allowed accuracy (Goals conceded accuracy)
    AT_Op_Shot_Acc = playing_stat.ATGC / playing_stat.ATSOT_A # AwayTeam shots allowed accuracy (Goals conceded accuracy)
    
    playing_stat['HT_Shot_Acc'] = HT_Shot_Acc
    playing_stat['AT_Shot_Acc'] = AT_Shot_Acc
    playing_stat['HT_Op_Shot_Acc'] = HT_Op_Shot_Acc
    playing_stat['AT_Op_Shot_Acc'] = AT_Op_Shot_Acc
    
    return playing_stat

In [17]:
for season in [ LaLiga_11_12_data,
            LaLiga_12_13_data, 
            LaLiga_13_14_data,
            LaLiga_14_15_data, 
            LaLiga_15_16_data, 
            LaLiga_16_17_data, 
            LaLiga_17_18_data, 
            LaLiga_18_19_data, 
            LaLiga_19_20_data, 
            LaLiga_20_21_data]:
    season = get_shots_acc(season)

## Cumulative points before specific match

In [18]:
# Function for getting specific number of points depends on the match result
def get_points(result):
    if result == 'W':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0

# Get match results for every team in every match week
def get_matchres(season):
    #print("here")
    # Create a dictionary with team names as keys
    teams = {}
    for i in season.groupby('HomeTeam').mean().T.columns:
        teams[i] = []

    # the value corresponding to keys is a list containing the match result
    for i in range(len(season)):
        if season.iloc[i].FTR == 'H':
            teams[season.iloc[i].HomeTeam].append('W')
            teams[season.iloc[i].AwayTeam].append('L') # If HomeTeam wins the AwayTeam lose so wee need to add L
        elif season.iloc[i].FTR == 'A':
            teams[season.iloc[i].AwayTeam].append('W')
            teams[season.iloc[i].HomeTeam].append('L') # If AwayTeam wins the HomeTeam lose so wee need to add L
        else:
            teams[season.iloc[i].AwayTeam].append('D')
            teams[season.iloc[i].HomeTeam].append('D')

            
    return pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T

# Get cumulative points connected with match results
def get_cuml_points(matchres):
    matchres_points = matchres.applymap(get_points)
    for i in range(2,38):
        matchres_points[i] = matchres_points[i] + matchres_points[i-1]
        
    matchres_points.insert(column =0, loc = 0, value = [0*i for i in range(20)])
    return matchres_points

# function summarizing and adding variables
def get_agg_points(season):
    matchres = get_matchres(season)
    cum_pts = get_cuml_points(matchres)
    HTP = []
    ATP = []

    for i in range(len(season)):
        ht = season.iloc[i].HomeTeam
        at = season.iloc[i].AwayTeam
        
        ht_match = season.iloc[i].HT_last_matches_number
        at_match = season.iloc[i].AT_last_matches_number
        
        HTP.append(cum_pts.loc[ht][ht_match])
        ATP.append(cum_pts.loc[at][at_match])
            
    season['HTP'] = HTP
    season['ATP'] = ATP
    return season

In [19]:
for season in seasons:
    season = get_agg_points(season)

## Current teams form with match results for 5 last games

In [20]:
# get and add to dataset last 5 match results
def add_form(playing_stat,num):
    form = get_matchres(playing_stat)
    
    for number in range(5+1): # I am interesing to 5 last games
        form[-number] = 'ND'  # No data
    
    HT_form = []
    AT_form = []
    
    for i in range(len(playing_stat)):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam

        ht_match = playing_stat.iloc[i].HT_last_matches_number
        at_match = playing_stat.iloc[i].AT_last_matches_number

        HT_form.append(form.loc[ht][ht_match - (num - 1)])
        AT_form.append(form.loc[at][at_match - (num - 1)])
        
    # every last match will have different variable  
    playing_stat['HM' + str(num)] = HT_form                 
    playing_stat['AM' + str(num)] = AT_form
    
    return playing_stat

# function summarizing and adding variables
def add_form_df(playing_statistics):
    playing_statistics = add_form(playing_statistics,1)
    playing_statistics = add_form(playing_statistics,2)
    playing_statistics = add_form(playing_statistics,3)
    playing_statistics = add_form(playing_statistics,4)
    playing_statistics = add_form(playing_statistics,5)
    return playing_statistics

In [21]:
for season in seasons:
    season = add_form_df(season)

## Cumulative number of wins, losses nad draws before specific match

In [22]:
# Binary variables connected with match results
def get_losses(result):
    if result == 'L':
        return 1
    elif result == 'D' or  result == 'W':
        return 0
    else:
        return np.nan     

def get_wins(result):
    if result == 'W':
        return 1
    elif result == 'L' or  result == 'D':
        return 0
    else:
        return np.nan 

def get_draws(result):
    if result == 'D':
        return 1
    elif result == 'L' or  result == 'W':
        return 0
    else:
        return np.nan 
    
# Get cumulative results during specific season
def get_agg_results(season):
    matchres = get_matchres(season)
    cum_wins = matchres.applymap(get_wins).cumsum(axis=1)
    cum_losses = matchres.applymap(get_losses).cumsum(axis=1)
    cum_draws = matchres.applymap(get_draws).cumsum(axis=1)
    
    cum_wins[0] = 0
    cum_losses[0] = 0
    cum_draws[0] = 0
    
    HT_cum_wins = []
    AT_cum_wins = []
    
    HT_cum_losses = []
    AT_cum_losses = []
    
    HT_cum_draws = []
    AT_cum_draws = []
    
    for i in range(len(season)):
        ht = season.iloc[i].HomeTeam
        at = season.iloc[i].AwayTeam
        
        ht_match = season.iloc[i].HT_last_matches_number
        at_match = season.iloc[i].AT_last_matches_number
        
        HT_cum_wins.append(cum_wins.loc[ht][ht_match])
        AT_cum_wins.append(cum_wins.loc[at][at_match])
        
        HT_cum_losses.append(cum_losses.loc[ht][ht_match])
        AT_cum_losses.append(cum_losses.loc[at][at_match])
        
        HT_cum_draws.append(cum_draws.loc[ht][ht_match])
        AT_cum_draws.append(cum_draws.loc[at][at_match])
            
    season['HT_cum_wins'] = HT_cum_wins
    season['AT_cum_wins'] = AT_cum_wins
    
    season['HT_cum_losses'] = HT_cum_losses
    season['AT_cum_losses'] = AT_cum_losses
    
    season['HT_cum_draws'] = HT_cum_draws
    season['AT_cum_draws'] = AT_cum_draws
    
    return season

In [23]:
for season in seasons:
    season = get_agg_results(season)

## Offensive and Defensive strength

The entire calculation process is presented in the link below:
* [Calcuation process](https://help.smarkets.com/hc/en-gb/articles/115001457989-How-to-calculate-Poisson-distribution-for-football-betting)

In [24]:
def get_off_def_strength(playing_stat):
    
    List_off_strength_HT = []
    List_def_strength_HT = []
    List_off_strength_AT = []
    List_def_strength_AT = []

    for i in range(len(playing_stat)):
        df_specific_match = playing_stat.iloc[i]
        df_day_before_SpecMat = playing_stat[playing_stat.Date < df_specific_match.Date]

        ht = df_specific_match.HomeTeam
        at = df_specific_match.AwayTeam

        Avg_score_Home = np.mean(df_day_before_SpecMat.FTHG) if np.mean(df_day_before_SpecMat.FTHG) !=0 else np.nan
        Avg_score_Away = np.mean(df_day_before_SpecMat.FTAG) if np.mean(df_day_before_SpecMat.FTAG) !=0 else np.nan

        Avg_conced_Home = Avg_score_Away
        Avg_conced_Away = Avg_score_Home

        # Home Team offensive strength
        Avg_home_goals_scored_by_HT = df_day_before_SpecMat[(df_day_before_SpecMat.HomeTeam == ht)].FTHG.mean()
        Off_strength_HT = Avg_home_goals_scored_by_HT / Avg_score_Home

        # Away Team defensive strength
        Avg_away_goals_conceded_by_AT = df_day_before_SpecMat[(df_day_before_SpecMat.AwayTeam == at)].FTHG.mean()
        Def_strength_AT = Avg_away_goals_conceded_by_AT / Avg_conced_Away

        List_off_strength_HT.append(Off_strength_HT)
        List_def_strength_AT.append(Def_strength_AT)

        # Away Team offensive strength
        Avg_away_goals_scored_by_AT = df_day_before_SpecMat[(df_day_before_SpecMat.AwayTeam == at)].FTAG.mean()
        Off_strength_AT = Avg_away_goals_scored_by_AT / Avg_score_Away

        # Home Team defensive strength
        Avg_home_goals_conceded_by_HT = df_day_before_SpecMat[(df_day_before_SpecMat.HomeTeam == ht)].FTAG.mean()
        Def_strength_HT = Avg_home_goals_conceded_by_HT / Avg_conced_Home

        List_off_strength_AT.append(Off_strength_AT)
        List_def_strength_HT.append(Def_strength_HT)
  
    playing_stat['Off_strength_HT'] = List_off_strength_HT
    playing_stat['Def_strength_HT'] = List_def_strength_HT
    playing_stat['Off_strength_AT'] = List_off_strength_AT
    playing_stat['Def_strength_AT'] = List_def_strength_AT

In [25]:
for season in seasons:
    season = get_off_def_strength(season)

## League position from last season

In European football leauges every season teams (usually 3 but it depends) can get promotion to the highest league and other teams can fall out. This way we get different teams every seasons. So to get league postion from last season I decided to assign to new teams a specific postion:
* number of teams in the highest league + new team's league postion from the second highest league
* for example in 2020/21 season Huesca was new team and they have 1st postion in 2019/20 season in the second highest league so I assign number 21

In [26]:
Standings = pd.read_csv('league_tables/LaLiga_table_rank.csv', sep=';')
Standings.set_index(['Team'], inplace=True)

In [27]:
# Add variables with last league postion
def get_last(playing_stat, Standings, year):
    HomeTeamLP = []
    AwayTeamLP = []
    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HomeTeamLP.append(Standings.loc[ht][year])
        AwayTeamLP.append(Standings.loc[at][year])
    playing_stat['HomeTeamLP'] = HomeTeamLP
    playing_stat['AwayTeamLP'] = AwayTeamLP
    return playing_stat

In [28]:
LaLiga_11_12_data = get_last(LaLiga_11_12_data, Standings, '2010/11')
LaLiga_12_13_data = get_last(LaLiga_12_13_data, Standings, '2011/12')
LaLiga_13_14_data = get_last(LaLiga_13_14_data, Standings, '2012/13')
LaLiga_14_15_data = get_last(LaLiga_14_15_data, Standings, '2013/14')
LaLiga_15_16_data = get_last(LaLiga_15_16_data, Standings, '2014/15')
LaLiga_16_17_data = get_last(LaLiga_16_17_data, Standings, '2015/16')
LaLiga_17_18_data = get_last(LaLiga_17_18_data, Standings, '2016/17')
LaLiga_18_19_data = get_last(LaLiga_18_19_data, Standings, '2017/18')
LaLiga_19_20_data = get_last(LaLiga_19_20_data, Standings, '2018/19')
LaLiga_20_21_data = get_last(LaLiga_20_21_data, Standings, '2019/20')

In [29]:
# adding binary variable if specific team is a new team in specific season
def get_newTeam(playing_stat):
    
    teams_number = len(playing_stat.HomeTeam.unique())
    
    playing_stat['Is_HT_newTeam'] = [1 if x > teams_number else 0 for x in playing_stat.HomeTeamLP]
    playing_stat['Is_AT_newTeam'] = [1 if x > teams_number else 0 for x in playing_stat.AwayTeamLP]
    
    return playing_stat

In [30]:
# Data was only for the last 10 completed season so I cant use every historical dataset
for season in [ LaLiga_11_12_data,
            LaLiga_12_13_data, 
            LaLiga_13_14_data,
            LaLiga_14_15_data, 
            LaLiga_15_16_data, 
            LaLiga_16_17_data, 
            LaLiga_17_18_data, 
            LaLiga_18_19_data, 
            LaLiga_19_20_data, 
            LaLiga_20_21_data]:
    season = get_newTeam(season)

In [31]:
# Checking if everything is correct
for season in [ LaLiga_11_12_data,
            LaLiga_12_13_data, 
            LaLiga_13_14_data,
            LaLiga_14_15_data, 
            LaLiga_15_16_data, 
            LaLiga_16_17_data, 
            LaLiga_17_18_data, 
            LaLiga_18_19_data, 
            LaLiga_19_20_data, 
            LaLiga_20_21_data]:
    print(season[season.HomeTeamLP > 20].HomeTeam.unique())

['Granada' 'Betis' 'Vallecano']
['Celta' 'La Coruna' 'Valladolid']
['Almeria' 'Elche' 'Villarreal']
['Eibar' 'Cordoba' 'La Coruna']
['Betis' 'Sp Gijon' 'Las Palmas']
['Leganes' 'Osasuna' 'Alaves']
['Girona' 'Levante' 'Getafe']
['Vallecano' 'Valladolid' 'Huesca']
['Mallorca' 'Granada' 'Osasuna']
['Cadiz' 'Huesca' 'Elche']

## Team data for every season from transfermarkt
* Average age
* Number of foreigners
* Average market value in milions of Euro
* Total market value in milions of Euro

Example data from 2016/17 season:
https://www.transfermarkt.com/laliga/startseite/wettbewerb/ES1/plus/?saison_id=2016

In [32]:
LaLiga_budget = pd.read_csv("budget_data/LaLiga_transfermaket_data.csv", sep=';')
LaLiga_budget.set_index(['Club'], inplace=True)
LaLiga_budget

,Avg_age,Foreigners,Avg_market_value_MLN_EUR,Total_market_value_MLN_EUR,Season
Club,,,,,
Barcelona,"24,9",11,"17,66","618,2",2011/12
Real Madrid,"24,4",16,"15,86","539,2",2011/12
Ath Madrid,"24,4",17,"5,68",210,2011/12
Valencia,"25,6",13,"6,46",181,2011/12
Ath Bilbao,"25,2",2,"4,81","144,2",2011/12
...,...,...,...,...,...
Alaves,"25,6",10,"2,28","79,8",2020/21
Huesca,"26,5",8,"1,89","64,1",2020/21
Valladolid,"26,9",9,"1,62","63,05",2020/21
Cadiz,"27,2",16,"1,16","47,65",2020/21
Elche,"26,7",14,"1,09","45,65",2020/21

Changing string variables for float

In [33]:
LaLiga_budget['Avg_age'].replace(',', '.', regex=True, inplace=True)
LaLiga_budget['Avg_market_value_MLN_EUR'].replace(',', '.', regex=True, inplace=True)
LaLiga_budget['Total_market_value_MLN_EUR'].replace(',', '.', regex=True, inplace=True)

In [34]:
LaLiga_budget.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, Barcelona to Elche
Data columns (total 5 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Avg_age                     200 non-null    object
 1   Foreigners                  200 non-null    int64
 2   Avg_market_value_MLN_EUR    200 non-null    object
 3   Total_market_value_MLN_EUR  200 non-null    object
 4   Season                      200 non-null    object
dtypes: int64(1), object(4)
memory usage: 9.4+ KB

In [35]:
LaLiga_budget.Avg_age = LaLiga_budget.Avg_age.astype(float)
LaLiga_budget.Avg_market_value_MLN_EUR = LaLiga_budget.Avg_market_value_MLN_EUR.astype(float)
LaLiga_budget.Total_market_value_MLN_EUR = LaLiga_budget.Total_market_value_MLN_EUR.astype(float)

In [36]:
# function summarizing and adding variables
def get_transfermarkt_data(season_data, Budget):
    
    HomeTeam_TM_avg_age = []
    HomeTeam_TM_foreigners_number = []
    HomeTeam_TM_avg_market_value_MLN_EUR = []
    HomeTeam_TM_total_market_value_MLN_EUR = []
    
    AwayTeam_TM_avg_age = []
    AwayTeam_TM_foreigners_number = []
    AwayTeam_TM_avg_market_value_MLN_EUR = []
    AwayTeam_TM_total_market_value_MLN_EUR = []
    
    for season in list(season_data.Season.unique()):
        
        LaLiga_budget_season = Budget[Budget.Season == season]
        
        for i in range(380):
            
            home_team = season_data[season_data.Season == season].iloc[i].HomeTeam
            away_team = season_data[season_data.Season == season].iloc[i].AwayTeam
            
            HomeTeam_TM_avg_age.append(LaLiga_budget_season.loc[home_team]['Avg_age'])
            HomeTeam_TM_foreigners_number.append(LaLiga_budget_season.loc[home_team]['Foreigners'])
            HomeTeam_TM_avg_market_value_MLN_EUR.append(LaLiga_budget_season.loc[home_team]['Avg_market_value_MLN_EUR'])
            HomeTeam_TM_total_market_value_MLN_EUR.append(LaLiga_budget_season.loc[home_team]['Total_market_value_MLN_EUR'])
            
            AwayTeam_TM_avg_age.append(LaLiga_budget_season.loc[away_team]['Avg_age'])
            AwayTeam_TM_foreigners_number.append(LaLiga_budget_season.loc[away_team]['Foreigners'])
            AwayTeam_TM_avg_market_value_MLN_EUR.append(LaLiga_budget_season.loc[away_team]['Avg_market_value_MLN_EUR'])
            AwayTeam_TM_total_market_value_MLN_EUR.append(LaLiga_budget_season.loc[away_team]['Total_market_value_MLN_EUR'])
            
            
    season_data['HomeTeam_TM_avg_age'] = HomeTeam_TM_avg_age
    season_data['HomeTeam_TM_foreigners_number'] = HomeTeam_TM_foreigners_number
    season_data['HomeTeam_TM_avg_market_value_MLN_EUR'] = HomeTeam_TM_avg_market_value_MLN_EUR
    season_data['HomeTeam_TM_total_market_value_MLN_EUR'] = HomeTeam_TM_total_market_value_MLN_EUR
    
    season_data['AwayTeam_TM_avg_age'] = AwayTeam_TM_avg_age
    season_data['AwayTeam_TM_foreigners_number'] = AwayTeam_TM_foreigners_number
    season_data['AwayTeam_TM_avg_market_value_MLN_EUR'] = AwayTeam_TM_avg_market_value_MLN_EUR
    season_data['AwayTeam_TM_total_market_value_MLN_EUR'] = AwayTeam_TM_total_market_value_MLN_EUR
    
    return season_data

In [37]:
for season in [LaLiga_11_12_data, LaLiga_12_13_data, LaLiga_13_14_data, LaLiga_14_15_data, LaLiga_15_16_data, 
              LaLiga_16_17_data, LaLiga_17_18_data, LaLiga_18_19_data, LaLiga_19_20_data, LaLiga_20_21_data]:
    
    get_transfermarkt_data(season, LaLiga_budget)

## Data concatenating

In [38]:
LaLiga_data = pd.concat([LaLiga_00_01_data, 
                      LaLiga_01_02_data, 
                      LaLiga_02_03_data, 
                      LaLiga_03_04_data, 
                      LaLiga_04_05_data, 
                      LaLiga_05_06_data, 
                      LaLiga_06_07_data, 
                      LaLiga_07_08_data, 
                      LaLiga_08_09_data, 
                      LaLiga_09_10_data, 
                      LaLiga_10_11_data, 
                      LaLiga_11_12_data,
                      LaLiga_12_13_data, 
                      LaLiga_13_14_data,
                      LaLiga_14_15_data, 
                      LaLiga_15_16_data, 
                      LaLiga_16_17_data, 
                      LaLiga_17_18_data, 
                      LaLiga_18_19_data, 
                      LaLiga_19_20_data, 
                      LaLiga_20_21_data], ignore_index=True)

In [39]:
# deleting unnecessary data
del LaLiga_00_01_data, LaLiga_01_02_data, LaLiga_02_03_data, LaLiga_03_04_data, LaLiga_04_05_data, LaLiga_05_06_data
del LaLiga_06_07_data, LaLiga_07_08_data, LaLiga_08_09_data, LaLiga_09_10_data
del season, seasons

## Calcuating betting odds
* 1x (Home win or Draw) = 100 / (100/Home_win_odds + 100/Draw_odds)
* x2 (Away win or Draw) = 100 / (100/Away_win_odds + 100/Draw_odds)

In [40]:
def get_more_odds(playing_stat):
    x1 = []
    x2 = []
    
    for i, row in playing_stat.iterrows():
        b365_H = playing_stat.iloc[i]['B365H']
        b365_D = playing_stat.iloc[i]['B365D']
        b365_A = playing_stat.iloc[i]['B365A']
        
        odd_H = 100/b365_H
        odd_D = 100/b365_D
        odd_A = 100/b365_A
        
        b365_H_D = round((100/(odd_H + odd_D)), 2)
        b365_A_D = round((100/(odd_A + odd_D)), 2)
        
        x1.append(b365_H_D)
        x2.append(b365_A_D)
        
    
    playing_stat['B365_HD'] = x1
    playing_stat['B365_AD'] = x2
    
    return playing_stat

In [41]:
get_more_odds(LaLiga_data)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,Season,HT_last_matches_number,AT_last_matches_number,...,HomeTeam_TM_avg_age,HomeTeam_TM_foreigners_number,HomeTeam_TM_avg_market_value_MLN_EUR,HomeTeam_TM_total_market_value_MLN_EUR,AwayTeam_TM_avg_age,AwayTeam_TM_foreigners_number,AwayTeam_TM_avg_market_value_MLN_EUR,AwayTeam_TM_total_market_value_MLN_EUR,B365_HD,B365_AD
0,SP1,2000-09-09,Barcelona,Malaga,2,1,H,2000/01,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,2000-09-09,La Coruna,Ath Bilbao,2,0,H,2000/01,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,2000-09-09,Real Madrid,Valencia,2,1,H,2000/01,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,2000-09-09,Sociedad,Santander,2,2,D,2000/01,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,2000-09-09,Zaragoza,Espanol,1,2,A,2000/01,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7975,SP1,2021-05-22,Osasuna,Sociedad,0,1,A,2020/21,37,37,...,27.0,7.0,2.69,96.75,24.7,6.0,10.70,406.6,2.32,1.17
7976,SP1,2021-05-22,Real Madrid,Villarreal,2,1,H,2020/21,37,37,...,24.8,17.0,21.28,787.30,25.9,13.0,8.13,292.6,1.09,2.83
7977,SP1,2021-05-22,Valladolid,Ath Madrid,1,2,A,2020/21,37,37,...,26.9,9.0,1.62,63.05,24.9,21.0,19.82,773.1,3.32,1.06
7978,SP1,2021-05-23,Granada,Getafe,0,0,D,2020/21,37,37,...,24.9,17.0,2.79,122.65,25.4,19.0,5.15,170.1,1.48,1.47
7979,SP1,2021-05-23,Sevilla,Alaves,1,0,H,2020/21,37,37,...,25.6,17.0,11.01,418.25,25.6,10.0,2.28,79.8,1.11,2.60

## Add points collect by teams from last 3 and 5 games

In [42]:
# Gets the form points.
def get_form_points(string):
    sum = 0
    for letter in string:
        sum += get_points(letter) # using other function
    return sum

In [43]:
# Concatenate variables with last team's results
LaLiga_data['HT_3match_FormPtsStr'] = LaLiga_data['HM1'] + LaLiga_data['HM2'] + LaLiga_data['HM3']
LaLiga_data['AT_3match_FormPtsStr'] = LaLiga_data['AM1'] + LaLiga_data['AM2'] + LaLiga_data['AM3']

LaLiga_data['HT_5match_FormPtsStr'] = LaLiga_data['HM1'] + LaLiga_data['HM2'] + LaLiga_data['HM3'] + LaLiga_data['HM4'] + LaLiga_data['HM5']
LaLiga_data['AT_5match_FormPtsStr'] = LaLiga_data['AM1'] + LaLiga_data['AM2'] + LaLiga_data['AM3'] + LaLiga_data['AM4'] + LaLiga_data['AM5']

# Applying function to get points
LaLiga_data['HT_3match_FormPts'] = LaLiga_data['HT_3match_FormPtsStr'].apply(get_form_points)
LaLiga_data['AT_3match_FormPts'] = LaLiga_data['AT_3match_FormPtsStr'].apply(get_form_points)

LaLiga_data['HT_5match_FormPts'] = LaLiga_data['HT_5match_FormPtsStr'].apply(get_form_points)
LaLiga_data['AT_5match_FormPts'] = LaLiga_data['AT_5match_FormPtsStr'].apply(get_form_points)

## Win or loss streaks

In [44]:
# Identify Win/Loss Streaks if any.
def get_3game_ws(string):
    if string == 'WWW':
        return 1
    else:
        return 0
    
def get_5game_ws(string):
    if string == 'WWWWW':
        return 1
    else:
        return 0
    
def get_3game_ls(string):
    if string == 'LLL':
        return 1
    else:
        return 0
    
def get_5game_ls(string):
    if string == 'LLLLL':
        return 1
    else:
        return 0

In [45]:
LaLiga_data['HTWinStreak3'] = LaLiga_data['HT_3match_FormPtsStr'].apply(get_3game_ws)
LaLiga_data['HTWinStreak5'] = LaLiga_data['HT_5match_FormPtsStr'].apply(get_5game_ws)
LaLiga_data['HTLossStreak3'] = LaLiga_data['HT_3match_FormPtsStr'].apply(get_3game_ls)
LaLiga_data['HTLossStreak5'] = LaLiga_data['HT_5match_FormPtsStr'].apply(get_5game_ls)

LaLiga_data['ATWinStreak3'] = LaLiga_data['AT_3match_FormPtsStr'].apply(get_3game_ws)
LaLiga_data['ATWinStreak5'] = LaLiga_data['AT_5match_FormPtsStr'].apply(get_5game_ws)
LaLiga_data['ATLossStreak3'] = LaLiga_data['AT_3match_FormPtsStr'].apply(get_3game_ls)
LaLiga_data['ATLossStreak5'] = LaLiga_data['AT_5match_FormPtsStr'].apply(get_5game_ls)

## Head to Head (H2H) variables
* Getting last 3 head to head match results and change it for points

In [46]:
def h2h(playing_stat):
    
    playing_stat["H2H_Home"] = ""
    playing_stat["H2H_Away"] = ""

    for i in range(1,len(playing_stat)):
        # get teams from specifc match and all data before this match
        df = playing_stat.iloc[0:i-1,]
        ht = playing_stat.loc[i,"HomeTeam"]
        at = playing_stat.loc[i,"AwayTeam"]
        
        # getting last 3 head to head matches
        dff = df[(((df.HomeTeam == ht) &  (df.AwayTeam == at)) | ((df.HomeTeam == at) &  (df.AwayTeam == ht)))].tail(3)
        
        # using data with minimum 1 head to head match
        if (len(dff) >= 1):
            for j in range(0,len(dff)):
                # Consider all possible scenarios
                if ((dff.iloc[j].HomeTeam == ht)  and (dff.iloc[j]["FTR"] == "H")):
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] += "W"
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] += "L"
                elif ((dff.iloc[j].HomeTeam == at)  and (dff.iloc[j]["FTR"] == "H")):
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] += "L"
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] += "W"
                elif ((dff.iloc[j].HomeTeam == ht)  and (dff.iloc[j]["FTR"] == "A")):
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] += "L"
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] += "W"
                elif ((dff.iloc[j].HomeTeam == at)  and (dff.iloc[j]["FTR"] == "A")):
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] += "W"
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] += "L"
                elif ((dff.iloc[j].HomeTeam == ht)  and (dff.iloc[j]["FTR"] == "D")):
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] += "D"
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] += "D"
                elif ((dff.iloc[j].HomeTeam == at)  and (dff.iloc[j]["FTR"] == "D")):
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] += "D"
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] += "D"
                    
        # if there was no match beetwen the teams get 'ND'
        else: 
            playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] = "ND"
            playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] = "ND"
    return playing_stat


# Calculating points for Home and Away teams in head to head matches and adding variables
def get_points_h2h(playing_stat, col):
    
    playing_stat[col+"_pts"] = 0
    
    for i in range(1,len(playing_stat)):
        if (len(playing_stat.iloc[i][col]) == 1):
            if playing_stat.iloc[i][col][0] =='L':
                playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] += 0
            elif playing_stat.iloc[i][col][0] =='W':
                playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] +=  3
            else:
                playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] +=  1
        elif (len(playing_stat.iloc[i][col]) == 2):
            for j in range(0,2):
                if playing_stat.iloc[i][col][j] =='L':
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] += 0
                elif playing_stat.iloc[i][col][j] =='W':
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] +=  3
                elif playing_stat.iloc[i][col][j] =='D':
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] +=  1
                else:
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] += 0
        elif (len(playing_stat.iloc[i][col]) == 3):
            for j in range(0,3):
                if playing_stat.iloc[i][col][j] =='L':
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] += 0
                elif playing_stat.iloc[i][col][j] =='W':
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] +=  3
                elif playing_stat.iloc[i][col][j] =='D':
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] +=  1
        else:
            playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] = 0
    
    return playing_stat

In [47]:
h2h(LaLiga_data)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,Season,HT_last_matches_number,AT_last_matches_number,...,HTWinStreak3,HTWinStreak5,HTLossStreak3,HTLossStreak5,ATWinStreak3,ATWinStreak5,ATLossStreak3,ATLossStreak5,H2H_Home,H2H_Away
0,SP1,2000-09-09,Barcelona,Malaga,2,1,H,2000/01,0,0,...,0,0,0,0,0,0,0,0,,
1,SP1,2000-09-09,La Coruna,Ath Bilbao,2,0,H,2000/01,0,0,...,0,0,0,0,0,0,0,0,ND,ND
2,SP1,2000-09-09,Real Madrid,Valencia,2,1,H,2000/01,0,0,...,0,0,0,0,0,0,0,0,ND,ND
3,SP1,2000-09-09,Sociedad,Santander,2,2,D,2000/01,0,0,...,0,0,0,0,0,0,0,0,ND,ND
4,SP1,2000-09-09,Zaragoza,Espanol,1,2,A,2000/01,0,0,...,0,0,0,0,0,0,0,0,ND,ND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7975,SP1,2021-05-22,Osasuna,Sociedad,0,1,A,2020/21,37,37,...,0,0,0,0,0,0,0,0,LDD,WDD
7976,SP1,2021-05-22,Real Madrid,Villarreal,2,1,H,2020/21,37,37,...,0,0,0,0,0,0,0,0,DWD,DLD
7977,SP1,2021-05-22,Valladolid,Ath Madrid,1,2,A,2020/21,37,37,...,0,0,1,0,0,0,0,0,DLL,DWW
7978,SP1,2021-05-23,Granada,Getafe,0,0,D,2020/21,37,37,...,0,0,1,0,0,0,0,0,LWW,WLL
7979,SP1,2021-05-23,Sevilla,Alaves,1,0,H,2020/21,37,37,...,0,0,0,0,0,0,0,0,WDW,LDL

In [48]:
get_points_h2h(LaLiga_data, "H2H_Home") 
get_points_h2h(LaLiga_data, "H2H_Away")

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,Season,HT_last_matches_number,AT_last_matches_number,...,HTLossStreak3,HTLossStreak5,ATWinStreak3,ATWinStreak5,ATLossStreak3,ATLossStreak5,H2H_Home,H2H_Away,H2H_Home_pts,H2H_Away_pts
0,SP1,2000-09-09,Barcelona,Malaga,2,1,H,2000/01,0,0,...,0,0,0,0,0,0,,,0,0
1,SP1,2000-09-09,La Coruna,Ath Bilbao,2,0,H,2000/01,0,0,...,0,0,0,0,0,0,ND,ND,1,1
2,SP1,2000-09-09,Real Madrid,Valencia,2,1,H,2000/01,0,0,...,0,0,0,0,0,0,ND,ND,1,1
3,SP1,2000-09-09,Sociedad,Santander,2,2,D,2000/01,0,0,...,0,0,0,0,0,0,ND,ND,1,1
4,SP1,2000-09-09,Zaragoza,Espanol,1,2,A,2000/01,0,0,...,0,0,0,0,0,0,ND,ND,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7975,SP1,2021-05-22,Osasuna,Sociedad,0,1,A,2020/21,37,37,...,0,0,0,0,0,0,LDD,WDD,2,5
7976,SP1,2021-05-22,Real Madrid,Villarreal,2,1,H,2020/21,37,37,...,0,0,0,0,0,0,DWD,DLD,5,2
7977,SP1,2021-05-22,Valladolid,Ath Madrid,1,2,A,2020/21,37,37,...,1,0,0,0,0,0,DLL,DWW,1,7
7978,SP1,2021-05-23,Granada,Getafe,0,0,D,2020/21,37,37,...,1,0,0,0,0,0,LWW,WLL,6,3
7979,SP1,2021-05-23,Sevilla,Alaves,1,0,H,2020/21,37,37,...,0,0,0,0,0,0,WDW,LDL,7,1

## Choose last 10 completed seasons

In [49]:
LaLiga_data = LaLiga_data[LaLiga_data.Season.isin(['2011/12', 
                                         '2012/13', 
                                         '2013/14', 
                                         '2014/15', 
                                         '2015/16', 
                                         '2016/17', 
                                         '2017/18', 
                                         '2018/19', 
                                         '2019/20', 
                                         '2020/21'])]

In [50]:
LaLiga_data.reset_index(drop=True, inplace=True)
LaLiga_data.shape

(3800, 85)

In [51]:
LaLiga_data_final = LaLiga_data[[
    'Div', 'Season', 'Date', 'HomeTeam', 'AwayTeam','FTHG', 'FTAG', 'FTR', 'HS','AS', 'HST', 'AST',
    'HT_last_matches_number', 'AT_last_matches_number', 'B365H', 'B365D', 'B365A', 'B365_HD', 'B365_AD',
    'HTGS', 'ATGS', 'HTGC', 'ATGC',
    'HTSOT_T','ATSOT_T', 'HTSOT_A', 'ATSOT_A', 
    'HT_Shot_Acc', 'AT_Shot_Acc','HT_Op_Shot_Acc', 'AT_Op_Shot_Acc',
    'HTP', 'ATP',
    'HT_cum_wins', 'AT_cum_wins', 'HT_cum_losses', 'AT_cum_losses', 'HT_cum_draws', 'AT_cum_draws',
    'Off_strength_HT', 'Def_strength_HT', 'Off_strength_AT', 'Def_strength_AT',
    'HM1', 'AM1', 'HM2', 'AM2', 'HM3', 'AM3', 'HM4', 'AM4', 'HM5', 'AM5',
    'HT_3match_FormPtsStr', 'AT_3match_FormPtsStr', 'HT_5match_FormPtsStr','AT_5match_FormPtsStr', 
    'HT_3match_FormPts', 'AT_3match_FormPts', 'HT_5match_FormPts', 'AT_5match_FormPts',
    'HTWinStreak3','HTWinStreak5', 'HTLossStreak3', 'HTLossStreak5', 
    'ATWinStreak3','ATWinStreak5', 'ATLossStreak3', 'ATLossStreak5',
    'HomeTeamLP', 'AwayTeamLP',
    'Is_HT_newTeam', 'Is_AT_newTeam',
    'H2H_Home', 'H2H_Away', 'H2H_Home_pts','H2H_Away_pts',
    'HomeTeam_TM_avg_age','HomeTeam_TM_foreigners_number', 
    'HomeTeam_TM_avg_market_value_MLN_EUR','HomeTeam_TM_total_market_value_MLN_EUR',
    'AwayTeam_TM_avg_age', 'AwayTeam_TM_foreigners_number', 
    'AwayTeam_TM_avg_market_value_MLN_EUR', 'AwayTeam_TM_total_market_value_MLN_EUR'
                          ]]

In [52]:
LaLiga_data_final.rename(columns={'HM1': 'HT_last_match1', 'AM1': 'AT_last_match1', 
                               'HM2': 'HT_last_match2', 'AM2': 'AT_last_match2', 
                               'HM3': 'HT_last_match3', 'AM3': 'AT_last_match3', 
                               'HM4': 'HT_last_match4', 'AM4': 'AT_last_match4', 
                               'HM5': 'HT_last_match5', 'AM5': 'AT_last_match5', 
                               'HomeTeamLP': 'HT_last_LP', 'AwayTeamLP': 'AT_last_LP', 
                               #'HTGD': 'HT_goal_diff', 'ATGD': 'AT_goal_diff', 
                               #'DiffLP': 'Diff_last_LP',
                               'HTP': 'HT_Pts', 'ATP': 'AT_Pts', 
                               'HTSOT_T': 'HT_Shots_OT_took','ATSOT_T': 'AT_Shots_OT_took', 
                               'HTSOT_A': 'HT_Shots_OT_allowed','ATSOT_A': 'AT_Shots_OT_allowed', 
                               'HT_Shot_Acc': 'HT_Shots_took_Acc', 'AT_Shot_Acc': 'AT_Shots_took_Acc',
                               'HT_Op_Shot_Acc': 'HT_Shots_allowed_Acc', 'AT_Op_Shot_Acc': 'AT_Shots_allowed_Acc'
                              }, inplace=True)

## Save created dataset

In [53]:
LaLiga_data_final.to_csv(path_or_buf= 'Final_data/LaLiga_data_final.csv', index=False)