## Uploading data and basic operations (add season variable and change the date format)

In [1]:
import numpy as np
import pandas as pd

In [2]:
league_code = 'I1'
seasons = ["00-01", "01-02", "02-03", "03-04", "04-05", 
          "05-06", "06-07", "07-08", "08-09", "09-10", 
          "10-11", "11-12", "12-13", "13-14", "14-15", 
          "15-16", "16-17", "17-18", "18-19", "19-20", "20-21"]

In [3]:
urls = []
for season in seasons:
    x = 'https://www.football-data.co.uk/mmz4281/' + season.replace("-", "") + '/'+league_code + '.csv'
    urls.append(x)

In [4]:
columns = ['Div', 'Date','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS', 'HST', 'AST', 'B365H', 'B365D', 'B365A']

I want to focus on the last 10 completed seasons (from 2011/12 to 2020/21) but i need more historical data to calculate H2H (Head To Head) variables

In some data from historical season there was no columns with shots data so I decided to also cut shots data from 00/01 to 10/11 season

In [5]:
SerieA_00_01_data = pd.read_csv(urls[0])[columns[0:-7]]
SerieA_01_02_data = pd.read_csv(urls[1])[columns[0:-7]]
SerieA_02_03_data = pd.read_csv(urls[2])[columns[0:-7]]
SerieA_03_04_data = pd.read_csv("match_data/I1_03_04.csv", sep=';')[columns[0:-7]] # Error Tokenizing Data with urls upload
SerieA_04_05_data = pd.read_csv("match_data/I1_04_05.csv", sep=';')[columns[0:-7]] # Error Tokenizing Data with urls upload
SerieA_05_06_data = pd.read_csv(urls[5])[columns[0:-7]]
SerieA_06_07_data = pd.read_csv(urls[6])[columns[0:-7]]
SerieA_07_08_data = pd.read_csv(urls[7])[columns[0:-7]]
SerieA_08_09_data = pd.read_csv(urls[8])[columns[0:-7]]
SerieA_09_10_data = pd.read_csv(urls[9])[columns[0:-7]]
SerieA_10_11_data = pd.read_csv(urls[10])[columns[0:-7]]
SerieA_11_12_data = pd.read_csv(urls[11])[columns]
SerieA_12_13_data = pd.read_csv(urls[12])[columns]
SerieA_13_14_data = pd.read_csv(urls[13])[columns]
SerieA_14_15_data = pd.read_csv(urls[14])[columns]
SerieA_15_16_data = pd.read_csv(urls[15])[columns]
SerieA_16_17_data = pd.read_csv(urls[16])[columns]
SerieA_17_18_data = pd.read_csv(urls[17])[columns]
SerieA_18_19_data = pd.read_csv(urls[18])[columns]
SerieA_19_20_data = pd.read_csv(urls[19])[columns]
SerieA_20_21_data = pd.read_csv(urls[20])[columns]

In [6]:
SerieA_20_21_data['Season'] = '2020/21'
SerieA_19_20_data['Season'] = '2019/20'
SerieA_18_19_data['Season'] = '2018/19'
SerieA_17_18_data['Season'] = '2017/18'
SerieA_16_17_data['Season'] = '2016/17'
SerieA_15_16_data['Season'] = '2015/16'
SerieA_14_15_data['Season'] = '2014/15'
SerieA_13_14_data['Season'] = '2013/14'
SerieA_12_13_data['Season'] = '2012/13'
SerieA_11_12_data['Season'] = '2011/12'
SerieA_10_11_data['Season'] = '2010/11'
SerieA_09_10_data['Season'] = '2009/10'
SerieA_08_09_data['Season'] = '2008/09'
SerieA_07_08_data['Season'] = '2007/08'
SerieA_06_07_data['Season'] = '2006/07'
SerieA_05_06_data['Season'] = '2005/06'
SerieA_04_05_data['Season'] = '2004/05'
SerieA_03_04_data['Season'] = '2003/04'
SerieA_02_03_data['Season'] = '2002/03'
SerieA_01_02_data['Season'] = '2001/02'
SerieA_00_01_data['Season'] = '2000/01'

In [7]:
seasons = [SerieA_00_01_data, SerieA_01_02_data, SerieA_02_03_data, SerieA_03_04_data, SerieA_04_05_data,
          SerieA_05_06_data, SerieA_06_07_data, SerieA_07_08_data, SerieA_08_09_data, SerieA_09_10_data, 
          SerieA_10_11_data, SerieA_11_12_data, SerieA_12_13_data, SerieA_13_14_data, SerieA_14_15_data, 
          SerieA_15_16_data, SerieA_16_17_data, SerieA_17_18_data, SerieA_18_19_data, SerieA_19_20_data, 
          SerieA_20_21_data]

In [8]:
# checking if every season was uploaded correctly without NA
for season in seasons:
    print(season.Season.unique())
    print(season.Date[0])
    season.dropna(inplace=True)
    print(len(season)) # in 00/01, 01/02 and 02/03 seasons there was 18 teams in the league
    print('|----------------------------|')

['2000/01']
30/09/00
306
|----------------------------|
['2001/02']
25/08/01
306
|----------------------------|
['2002/03']
14/09/02
306
|----------------------------|
['2003/04']
30.08.2003
306
|----------------------------|
['2004/05']
11.09.2004
380
|----------------------------|
['2005/06']
27/08/05
380
|----------------------------|
['2006/07']
09/09/06
380
|----------------------------|
['2007/08']
25/08/07
380
|----------------------------|
['2008/09']
30/08/08
380
|----------------------------|
['2009/10']
22/08/09
380
|----------------------------|
['2010/11']
28/08/10
380
|----------------------------|
['2011/12']
09/09/11
380
|----------------------------|
['2012/13']
25/08/12
379
|----------------------------|
['2013/14']
24/08/13
380
|----------------------------|
['2014/15']
30/08/14
380
|----------------------------|
['2015/16']
22/08/15
380
|----------------------------|
['2016/17']
20/08/16
380
|----------------------------|
['2017/18']
19/08/17
380
|----------------------------|
['2018/19']
18/08/2018
380
|----------------------------|
['2019/20']
24/08/2019
380
|----------------------------|
['2020/21']
19/09/2020
378
|----------------------------|

**No relevant data in 2012/13 and 2020/21 seasons!**

Upload data one more time

In [9]:
SerieA_00_01_data = pd.read_csv(urls[0])[columns[0:-7]]
SerieA_01_02_data = pd.read_csv(urls[1])[columns[0:-7]]
SerieA_02_03_data = pd.read_csv(urls[2])[columns[0:-7]]
SerieA_03_04_data = pd.read_csv("match_data/I1_03_04.csv", sep=';')[columns[0:-7]]
SerieA_04_05_data = pd.read_csv("match_data/I1_04_05.csv", sep=';')[columns[0:-7]]
SerieA_05_06_data = pd.read_csv(urls[5])[columns[0:-7]]
SerieA_06_07_data = pd.read_csv(urls[6])[columns[0:-7]]
SerieA_07_08_data = pd.read_csv(urls[7])[columns[0:-7]]
SerieA_08_09_data = pd.read_csv(urls[8])[columns[0:-7]]
SerieA_09_10_data = pd.read_csv(urls[9])[columns[0:-7]]
SerieA_10_11_data = pd.read_csv(urls[10])[columns[0:-7]]
SerieA_11_12_data = pd.read_csv(urls[11])[columns]
SerieA_12_13_data = pd.read_csv(urls[12])[columns]
SerieA_13_14_data = pd.read_csv(urls[13])[columns]
SerieA_14_15_data = pd.read_csv(urls[14])[columns]
SerieA_15_16_data = pd.read_csv(urls[15])[columns]
SerieA_16_17_data = pd.read_csv(urls[16])[columns]
SerieA_17_18_data = pd.read_csv(urls[17])[columns]
SerieA_18_19_data = pd.read_csv(urls[18])[columns]
SerieA_19_20_data = pd.read_csv(urls[19])[columns]
SerieA_20_21_data = pd.read_csv(urls[20])[columns]

#### Season 12/13

In [10]:
SerieA_12_13_data[SerieA_12_13_data.isna().any(axis=1)] # Match Cagliari-Roma was a walkover

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,B365H,B365D,B365A
34,I1,23/09/12,Cagliari,Roma,0.0,3.0,A,NaN,NaN,NaN,NaN,3.1,3.5,2.2
380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Fill in the statistics of shots in such a way that they do not disturb the accuracy calculated later

In [11]:
SerieA_12_13_data.loc[34, 'HS'] = 0
SerieA_12_13_data.loc[34, 'AS'] = 3
SerieA_12_13_data.loc[34, 'HST'] = 0
SerieA_12_13_data.loc[34, 'AST'] = 3

In [12]:
SerieA_12_13_data.loc[34]

Div               I1
Date        23/09/12
HomeTeam    Cagliari
AwayTeam        Roma
FTHG             0.0
FTAG             3.0
FTR                A
HS               0.0
AS               3.0
HST              0.0
AST              3.0
B365H            3.1
B365D            3.5
B365A            2.2
Name: 34, dtype: object

In [13]:
SerieA_12_13_data.dropna()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,B365H,B365D,B365A
0,I1,25/08/12,Fiorentina,Udinese,2.0,1.0,H,23.0,7.0,8.0,2.0,2.05,3.2,3.75
1,I1,25/08/12,Juventus,Parma,2.0,0.0,H,15.0,6.0,6.0,5.0,1.30,5.0,10.50
2,I1,26/08/12,Atalanta,Lazio,0.0,1.0,A,10.0,13.0,3.0,4.0,2.40,3.2,3.00
3,I1,26/08/12,Chievo,Bologna,2.0,0.0,H,6.0,4.0,3.0,1.0,2.10,3.2,3.60
4,I1,26/08/12,Genoa,Cagliari,2.0,0.0,H,15.0,17.0,4.0,4.0,1.95,3.3,4.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,I1,19/05/13,Palermo,Parma,1.0,3.0,A,22.0,12.0,10.0,8.0,2.25,3.2,3.30
376,I1,19/05/13,Pescara,Fiorentina,1.0,5.0,A,23.0,12.0,5.0,8.0,15.00,7.0,1.17
377,I1,19/05/13,Roma,Napoli,2.0,1.0,H,13.0,11.0,8.0,3.0,2.50,3.4,2.70
378,I1,19/05/13,Siena,Milan,1.0,2.0,A,8.0,21.0,2.0,9.0,13.00,6.5,1.20
379,I1,19/05/13,Torino,Catania,2.0,2.0,D,16.0,13.0,5.0,4.0,2.10,3.2,3.60

#### Season 2020/21

In [14]:
SerieA_20_21_data[SerieA_20_21_data.isna().any(axis=1)] # No betting odds

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,B365H,B365D,B365A
35,I1,18/10/2020,Udinese,Parma,3,2,H,9,7,4,3,NaN,NaN,NaN
37,I1,19/10/2020,Verona,Genoa,0,0,D,18,5,12,2,NaN,NaN,NaN

In [15]:
SerieA_20_21_data_all_col = pd.read_csv(urls[20]) # upload data with all columns

In [16]:
pd.set_option("display.max_columns", None)
SerieA_20_21_data_all_col[SerieA_20_21_data_all_col.isna().any(axis=1)]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,PSCH,PSCD,PSCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
35,I1,18/10/2020,17:00,Udinese,Parma,3,2,H,1,1,D,9,7,4,3,12,11,11,2,3,2,0,0,NaN,NaN,NaN,1.8,3.60,4.6,NaN,NaN,NaN,NaN,NaN,NaN,1.83,3.4,4.80,1.8,3.5,4.50,1.92,3.7,5.00,1.84,3.49,4.42,NaN,NaN,NaN,NaN,2.03,1.92,1.95,1.85,-0.5,NaN,NaN,NaN,NaN,1.90,2.06,1.85,2.01,1.90,3.5,4.00,1.91,3.50,4.20,2.00,3.25,3.90,2.02,3.49,4.07,2.00,3.40,4.00,1.95,3.3,4.10,2.06,3.60,4.38,1.98,3.44,3.96,2.00,1.9,1.99,1.89,2.03,2.05,1.95,1.86,-0.50,2.02,1.91,2.02,1.89,2.05,1.93,2.01,1.86
37,I1,19/10/2020,19:45,Verona,Genoa,0,0,D,0,0,D,18,5,12,2,14,15,14,2,1,4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.05,3.4,3.75,2.05,3.40,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.25,3.5,3.00,2.15,3.40,3.30,2.25,3.35,3.15,2.36,3.47,3.16,2.25,3.50,3.10,2.25,3.4,3.13,2.40,3.75,3.40,2.28,3.45,3.11,1.72,2.1,1.79,2.11,1.83,2.26,1.73,2.09,-0.25,2.03,1.87,2.03,1.88,2.06,1.94,2.00,1.87
40,I1,24/10/2020,17:00,Genoa,Inter,0,2,A,0,0,D,1,10,0,6,11,17,1,9,1,1,0,0,7.5,4.5,1.4,8.0,4.75,1.4,7.5,4.8,1.4,8.24,5.12,1.41,8.00,5.0,1.38,8.5,5.0,1.36,8.50,5.3,1.44,7.60,4.93,1.39,NaN,NaN,1.55,2.61,1.55,2.66,1.52,2.50,1.5,1.85,2.05,1.84,2.08,1.86,2.12,1.79,2.07,8.00,5.5,1.33,8.00,5.25,1.36,8.00,5.25,1.37,9.31,5.91,1.33,9.00,5.25,1.33,9.50,5.5,1.30,9.50,5.93,1.38,8.23,5.43,1.35,NaN,NaN,1.44,2.94,1.53,2.96,1.44,2.75,1.50,1.97,1.93,2.05,1.88,2.06,2.02,1.92,1.94

In [17]:
# Use average betting odds
odds_35 = SerieA_20_21_data_all_col[(SerieA_20_21_data_all_col.HomeTeam == 'Udinese') & 
                          (SerieA_20_21_data_all_col.AwayTeam == 'Parma')][['AvgH', 'AvgD', 'AvgA']]

odds_37 = SerieA_20_21_data_all_col[(SerieA_20_21_data_all_col.HomeTeam == 'Verona') & 
                          (SerieA_20_21_data_all_col.AwayTeam == 'Genoa')][['AvgH', 'AvgD', 'AvgA']]

In [18]:
SerieA_20_21_data.loc[37]

Div                 I1
Date        19/10/2020
HomeTeam        Verona
AwayTeam         Genoa
FTHG                 0
FTAG                 0
FTR                  D
HS                  18
AS                   5
HST                 12
AST                  2
B365H              NaN
B365D              NaN
B365A              NaN
Name: 37, dtype: object

In [19]:
SerieA_20_21_data.loc[35, 'B365H'] = odds_35.loc[35, 'AvgH']
SerieA_20_21_data.loc[35, 'B365D'] = odds_35.loc[35, 'AvgD']
SerieA_20_21_data.loc[35, 'B365A'] = odds_35.loc[35, 'AvgA']

SerieA_20_21_data.loc[37, 'B365H'] = odds_37.loc[37, 'AvgH']
SerieA_20_21_data.loc[37, 'B365D'] = odds_37.loc[37, 'AvgD']
SerieA_20_21_data.loc[37, 'B365A'] = odds_37.loc[37, 'AvgA']

In [20]:
SerieA_20_21_data[SerieA_20_21_data.isna().any(axis=1)]

Empty DataFrame
Columns: [Div, Date, HomeTeam, AwayTeam, FTHG, FTAG, FTR, HS, AS, HST, AST, B365H, B365D, B365A]
Index: []

In [21]:
seasons = [SerieA_00_01_data, SerieA_01_02_data, SerieA_02_03_data, SerieA_03_04_data, SerieA_04_05_data,
          SerieA_05_06_data, SerieA_06_07_data, SerieA_07_08_data, SerieA_08_09_data, SerieA_09_10_data, 
          SerieA_10_11_data, SerieA_11_12_data, SerieA_12_13_data, SerieA_13_14_data, SerieA_14_15_data, 
          SerieA_15_16_data, SerieA_16_17_data, SerieA_17_18_data, SerieA_18_19_data, SerieA_19_20_data, 
          SerieA_20_21_data]

In [22]:
# checking if every season was uploaded correctly without NA
for season in seasons:
    #print(season.Season.unique())
    print(season.Date[0])
    season.dropna(how='all' ,inplace=True)
    print(len(season))
    print('|----------------------------|')

30/09/00
306
|----------------------------|
25/08/01
306
|----------------------------|
14/09/02
306
|----------------------------|
30.08.2003
306
|----------------------------|
11.09.2004
380
|----------------------------|
27/08/05
380
|----------------------------|
09/09/06
380
|----------------------------|
25/08/07
380
|----------------------------|
30/08/08
380
|----------------------------|
22/08/09
380
|----------------------------|
28/08/10
380
|----------------------------|
09/09/11
380
|----------------------------|
25/08/12
380
|----------------------------|
24/08/13
380
|----------------------------|
30/08/14
380
|----------------------------|
22/08/15
380
|----------------------------|
20/08/16
380
|----------------------------|
19/08/17
380
|----------------------------|
18/08/2018
380
|----------------------------|
24/08/2019
380
|----------------------------|
19/09/2020
380
|----------------------------|

In [23]:
SerieA_20_21_data['Season'] = '2020/21'
SerieA_19_20_data['Season'] = '2019/20'
SerieA_18_19_data['Season'] = '2018/19'
SerieA_17_18_data['Season'] = '2017/18'
SerieA_16_17_data['Season'] = '2016/17'
SerieA_15_16_data['Season'] = '2015/16'
SerieA_14_15_data['Season'] = '2014/15'
SerieA_13_14_data['Season'] = '2013/14'
SerieA_12_13_data['Season'] = '2012/13'
SerieA_11_12_data['Season'] = '2011/12'
SerieA_10_11_data['Season'] = '2010/11'
SerieA_09_10_data['Season'] = '2009/10'
SerieA_08_09_data['Season'] = '2008/09'
SerieA_07_08_data['Season'] = '2007/08'
SerieA_06_07_data['Season'] = '2006/07'
SerieA_05_06_data['Season'] = '2005/06'
SerieA_04_05_data['Season'] = '2004/05'
SerieA_03_04_data['Season'] = '2003/04'
SerieA_02_03_data['Season'] = '2002/03'
SerieA_01_02_data['Season'] = '2001/02'
SerieA_00_01_data['Season'] = '2000/01'

Simple checking corrected datasets

In [24]:
SerieA_20_21_data[SerieA_20_21_data.isna().any(axis=1)]

Empty DataFrame
Columns: [Div, Date, HomeTeam, AwayTeam, FTHG, FTAG, FTR, HS, AS, HST, AST, B365H, B365D, B365A, Season]
Index: []

In [25]:
SerieA_12_13_data[SerieA_12_13_data.isna().any(axis=1)]

Empty DataFrame
Columns: [Div, Date, HomeTeam, AwayTeam, FTHG, FTAG, FTR, HS, AS, HST, AST, B365H, B365D, B365A, Season]
Index: []

In [26]:
# Change Date Format
for season in seasons:
    season.Date = pd.to_datetime(season.Date, dayfirst=True)

## Adds the number of games played by the team before specific match

In [27]:
def get_last_matches_number(playing_stat):
    
    # Diffrent lists for HomeTeam and AwayTeam because sometimes number of games played before 
    # can be diffrent becasue of postponing the match
    HT_Match_number = []
    AT_Match_number = []
    
    # dataset iteration over each row
    for i, row in playing_stat.iterrows():
        df_nad = playing_stat.iloc[0:i]
        df_specific_match = playing_stat.iloc[i]

        ht = df_specific_match.HomeTeam
        at = df_specific_match.AwayTeam

        x = len(df_nad[(df_nad.HomeTeam == ht) | (df_nad.AwayTeam == ht)])
        y = len(df_nad[(df_nad.HomeTeam == at) | (df_nad.AwayTeam == at)])

        HT_Match_number.append(x)
        AT_Match_number.append(y)
        
    playing_stat['HT_last_matches_number'] = HT_Match_number
    playing_stat['AT_last_matches_number'] = AT_Match_number
    
    return playing_stat

In [28]:
# apply function on every season data
for season in seasons:
    season = get_last_matches_number(season)

## Goals scored and conceded before specific match

In [29]:
# Gets the goals scored aggregation arranged by teams and matchweek
def get_goals_scored(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        HTGS = playing_stat.iloc[i]['FTHG']
        ATGS = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGS)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGS)
        
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsScored = pd.DataFrame(data=teams, index = [i for i in range(1,len(teams.keys())*2-1)]).T
    GoalsScored[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,len(teams.keys())*2-1):
        GoalsScored[i] = GoalsScored[i] + GoalsScored[i-1]
    return GoalsScored

# Gets the goals conceded aggregation arranged by teams and matchweek
def get_goals_conceded(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
#         print("check {} \n".format(i))
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        ATGC = playing_stat.iloc[i]['FTHG']
        HTGC = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGC)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,len(teams.keys())*2-1)]).T
    GoalsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,len(teams.keys())*2-1):
        GoalsConceded[i] = GoalsConceded[i] + GoalsConceded[i-1]
    return GoalsConceded

# function summarizing and adding variables
def get_gss(playing_stat):
    GC = get_goals_conceded(playing_stat)
    GS = get_goals_scored(playing_stat)
   
    HTGS = []
    ATGS = []
    HTGC = []
    ATGC = []
    
    for i in range(len(playing_stat)):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam

        ht_match = playing_stat.iloc[i].HT_last_matches_number
        at_match = playing_stat.iloc[i].AT_last_matches_number

        HTGS.append(GS.loc[ht][ht_match])
        ATGS.append(GS.loc[at][at_match])
        
        HTGC.append(GC.loc[ht][ht_match])
        ATGC.append(GC.loc[at][at_match])
        
        
    playing_stat['HTGS'] = HTGS
    playing_stat['ATGS'] = ATGS
    playing_stat['HTGC'] = HTGC
    playing_stat['ATGC'] = ATGC
    
    return playing_stat

In [30]:
for season in seasons:
    season = get_gss(season)

## Shots on target took and allowed before specific match

In [31]:
# Gets the shots on target took aggregation arranged by teams and matchweek
def get_shots_on_target_took(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        HTSOT = playing_stat.iloc[i]['HST']
        ATSOT = playing_stat.iloc[i]['AST']
        teams[playing_stat.iloc[i].HomeTeam].append(HTSOT)
        teams[playing_stat.iloc[i].AwayTeam].append(ATSOT)
        
    # Create a dataframe for shots on target took where rows are teams and cols are matchweek.
    ShotsOT = pd.DataFrame(data=teams, index = [i for i in range(1,len(teams.keys())*2-1)]).T
    ShotsOT[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,len(teams.keys())*2-1):
        ShotsOT[i] = ShotsOT[i] + ShotsOT[i-1]
    return ShotsOT

# Gets the shots on target allowed aggregation arranged by teams and matchweek
def get_shots_on_target_allowed(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        ATSOT_A = playing_stat.iloc[i]['HST']
        HTSOT_A = playing_stat.iloc[i]['AST']
        teams[playing_stat.iloc[i].HomeTeam].append(HTSOT_A)
        teams[playing_stat.iloc[i].AwayTeam].append(ATSOT_A)
    
    # Create a dataframe for shots on target allowed where rows are teams and cols are matchweek.
    ShotsOT_Allowed = pd.DataFrame(data=teams, index = [i for i in range(1,len(teams.keys())*2-1)]).T
    ShotsOT_Allowed[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,len(teams.keys())*2-1):
        ShotsOT_Allowed[i] = ShotsOT_Allowed[i] + ShotsOT_Allowed[i-1]
    return ShotsOT_Allowed

# function summarizing and adding variables
def get_sot(playing_stat):
    SOT_T = get_shots_on_target_took(playing_stat)
    SOT_A = get_shots_on_target_allowed(playing_stat)
   
    HTSOT_T = []
    ATSOT_T = []
    HTSOT_A = []
    ATSOT_A = []
    
    for i in range(len(playing_stat)):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam

        ht_match = playing_stat.iloc[i].HT_last_matches_number
        at_match = playing_stat.iloc[i].AT_last_matches_number

        HTSOT_T.append(SOT_T.loc[ht][ht_match])
        ATSOT_T.append(SOT_T.loc[at][at_match])
        
        HTSOT_A.append(SOT_A.loc[ht][ht_match])
        ATSOT_A.append(SOT_A.loc[at][at_match])
        
        
    playing_stat['HTSOT_T'] = HTSOT_T
    playing_stat['ATSOT_T'] = ATSOT_T
    playing_stat['HTSOT_A'] = HTSOT_A
    playing_stat['ATSOT_A'] = ATSOT_A
    
    return playing_stat

In [32]:
# Datasets with shots data
for season in [ SerieA_11_12_data,
            SerieA_12_13_data, 
            SerieA_13_14_data,
            SerieA_14_15_data, 
            SerieA_15_16_data, 
            SerieA_16_17_data, 
            SerieA_17_18_data, 
            SerieA_18_19_data, 
            SerieA_19_20_data, 
            SerieA_20_21_data]:
    season = get_sot(season)

In [33]:
# Get shots accuracy
def get_shots_acc(playing_stat):
    
    HT_Shot_Acc = playing_stat.HTGS / playing_stat.HTSOT_T # HomeTeam shots took accuracy (Goals scoring accuracy)
    AT_Shot_Acc = playing_stat.ATGS / playing_stat.ATSOT_T # AwayTeam shots took accuracy (Goals scoring accuracy)
    
    HT_Op_Shot_Acc = playing_stat.HTGC / playing_stat.HTSOT_A # HomeTeam shots allowed accuracy (Goals conceded accuracy)
    AT_Op_Shot_Acc = playing_stat.ATGC / playing_stat.ATSOT_A # AwayTeam shots allowed accuracy (Goals conceded accuracy)
    
    playing_stat['HT_Shot_Acc'] = HT_Shot_Acc
    playing_stat['AT_Shot_Acc'] = AT_Shot_Acc
    playing_stat['HT_Op_Shot_Acc'] = HT_Op_Shot_Acc
    playing_stat['AT_Op_Shot_Acc'] = AT_Op_Shot_Acc
    
    return playing_stat

In [34]:
# Datasets with shots data
for season in [ SerieA_11_12_data,
            SerieA_12_13_data, 
            SerieA_13_14_data,
            SerieA_14_15_data, 
            SerieA_15_16_data, 
            SerieA_16_17_data, 
            SerieA_17_18_data, 
            SerieA_18_19_data, 
            SerieA_19_20_data, 
            SerieA_20_21_data]:
    season = get_shots_acc(season)

## Cumulative points before specific match

In [35]:
# Function for getting specific number of points depends on the match result
def get_points(result):
    if result == 'W':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0

# Get match results for every team in every match week
def get_matchres(season):
    # Create a dictionary with team names as keys
    teams = {}
    for i in season.groupby('HomeTeam').mean().T.columns:
        teams[i] = []

    # the value corresponding to keys is a list containing the match result
    for i in range(len(season)):
        if season.iloc[i].FTR == 'H':
            teams[season.iloc[i].HomeTeam].append('W')
            teams[season.iloc[i].AwayTeam].append('L')
        elif season.iloc[i].FTR == 'A':
            teams[season.iloc[i].AwayTeam].append('W')
            teams[season.iloc[i].HomeTeam].append('L')
        else:
            teams[season.iloc[i].AwayTeam].append('D')
            teams[season.iloc[i].HomeTeam].append('D')

            
    return pd.DataFrame(data=teams, index = [i for i in range(1,len(teams.keys())*2-1)]).T
    
# Get cumulative points connected with match results
def get_cuml_points(matchres):
    
    matchres_points = matchres.applymap(get_points)
    for i in range(2,len(matchres)*2-2):
        matchres_points[i] = matchres_points[i] + matchres_points[i-1]
        
    matchres_points.insert(column =0, loc = 0, value = [0*i for i in range(len(matchres))])
    return matchres_points

# function summarizing and adding variables
def get_agg_points(season):
    matchres = get_matchres(season)
    cum_pts = get_cuml_points(matchres)
    HTP = []
    ATP = []

    for i in range(len(season)):
        ht = season.iloc[i].HomeTeam
        at = season.iloc[i].AwayTeam
        
        ht_match = season.iloc[i].HT_last_matches_number
        at_match = season.iloc[i].AT_last_matches_number
        
        HTP.append(cum_pts.loc[ht][ht_match])
        ATP.append(cum_pts.loc[at][at_match])
            
    season['HTP'] = HTP
    season['ATP'] = ATP
    return season

In [36]:
for season in seasons:
    season = get_agg_points(season)

## Current teams form with match results for 5 last games

In [37]:
# get and add to dataset last 5 match results
def add_form(playing_stat,num):
    form = get_matchres(playing_stat)
    
    for number in range(5+1): # I am interesing to 5 last games
        form[-number] = 'ND'  # No data
    
    HT_form = []
    AT_form = []
    
    for i in range(len(playing_stat)):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam

        ht_match = playing_stat.iloc[i].HT_last_matches_number
        at_match = playing_stat.iloc[i].AT_last_matches_number

        HT_form.append(form.loc[ht][ht_match - (num - 1)])
        AT_form.append(form.loc[at][at_match - (num - 1)])

    # every last match will have different variable 
    playing_stat['HM' + str(num)] = HT_form                 
    playing_stat['AM' + str(num)] = AT_form
    
    return playing_stat

# function summarizing and adding variables
def add_form_df(playing_statistics):
    playing_statistics = add_form(playing_statistics,1)
    playing_statistics = add_form(playing_statistics,2)
    playing_statistics = add_form(playing_statistics,3)
    playing_statistics = add_form(playing_statistics,4)
    playing_statistics = add_form(playing_statistics,5)
    return playing_statistics

In [38]:
for season in seasons:
    season = add_form_df(season)

## Cumulative number of wins, losses nad draws before specific match

In [39]:
# Binary variables connected with match results
def get_losses(result):
    if result == 'L':
        return 1
    elif result == 'D' or  result == 'W':
        return 0
    else:
        return np.nan     

def get_wins(result):
    if result == 'W':
        return 1
    elif result == 'L' or  result == 'D':
        return 0
    else:
        return np.nan 

def get_draws(result):
    if result == 'D':
        return 1
    elif result == 'L' or  result == 'W':
        return 0
    else:
        return np.nan 
    
# Get cumulative results during specific season
def get_agg_results(season):
    matchres = get_matchres(season)
    cum_wins = matchres.applymap(get_wins).cumsum(axis=1)
    cum_losses = matchres.applymap(get_losses).cumsum(axis=1)
    cum_draws = matchres.applymap(get_draws).cumsum(axis=1)
    
    cum_wins[0] = 0
    cum_losses[0] = 0
    cum_draws[0] = 0
    
    HT_cum_wins = []
    AT_cum_wins = []
    
    HT_cum_losses = []
    AT_cum_losses = []
    
    HT_cum_draws = []
    AT_cum_draws = []
    
    for i in range(len(season)):
        ht = season.iloc[i].HomeTeam
        at = season.iloc[i].AwayTeam
        
        ht_match = season.iloc[i].HT_last_matches_number
        at_match = season.iloc[i].AT_last_matches_number
        
        HT_cum_wins.append(cum_wins.loc[ht][ht_match])
        AT_cum_wins.append(cum_wins.loc[at][at_match])
        
        HT_cum_losses.append(cum_losses.loc[ht][ht_match])
        AT_cum_losses.append(cum_losses.loc[at][at_match])
        
        HT_cum_draws.append(cum_draws.loc[ht][ht_match])
        AT_cum_draws.append(cum_draws.loc[at][at_match])
            
    season['HT_cum_wins'] = HT_cum_wins
    season['AT_cum_wins'] = AT_cum_wins
    
    season['HT_cum_losses'] = HT_cum_losses
    season['AT_cum_losses'] = AT_cum_losses
    
    season['HT_cum_draws'] = HT_cum_draws
    season['AT_cum_draws'] = AT_cum_draws
    
    return season

In [40]:
for season in seasons:
    season = get_agg_results(season)

## Offensive and Defensive strength

The entire calculation process is presented in the link below:
* [Calcuation process](https://help.smarkets.com/hc/en-gb/articles/115001457989-How-to-calculate-Poisson-distribution-for-football-betting)

In [41]:
def get_off_def_strength(playing_stat):

    List_off_strength_HT = []
    List_def_strength_HT = []
    List_off_strength_AT = []
    List_def_strength_AT = []

    for i in range(len(playing_stat)):
        df_specific_match = playing_stat.iloc[i]
        df_day_before_SpecMat = playing_stat[playing_stat.Date < df_specific_match.Date]

        ht = df_specific_match.HomeTeam
        at = df_specific_match.AwayTeam

        Avg_score_Home = np.mean(df_day_before_SpecMat.FTHG) if np.mean(df_day_before_SpecMat.FTHG) !=0 else np.nan
        Avg_score_Away = np.mean(df_day_before_SpecMat.FTAG) if np.mean(df_day_before_SpecMat.FTAG) !=0 else np.nan

        Avg_conced_Home = Avg_score_Away
        Avg_conced_Away = Avg_score_Home

        # Home Team offensive strength
        Avg_home_goals_scored_by_HT = df_day_before_SpecMat[(df_day_before_SpecMat.HomeTeam == ht)].FTHG.mean()
        Off_strength_HT = Avg_home_goals_scored_by_HT / Avg_score_Home

        # Away Team defensive strength
        Avg_away_goals_conceded_by_AT = df_day_before_SpecMat[(df_day_before_SpecMat.AwayTeam == at)].FTHG.mean()
        Def_strength_AT = Avg_away_goals_conceded_by_AT / Avg_conced_Away

        List_off_strength_HT.append(Off_strength_HT)
        List_def_strength_AT.append(Def_strength_AT)

        # Away Team offensive strength
        Avg_away_goals_scored_by_AT = df_day_before_SpecMat[(df_day_before_SpecMat.AwayTeam == at)].FTAG.mean()
        Off_strength_AT = Avg_away_goals_scored_by_AT / Avg_score_Away

        # Home Team defensive strength
        Avg_home_goals_conceded_by_HT = df_day_before_SpecMat[(df_day_before_SpecMat.HomeTeam == ht)].FTAG.mean()
        Def_strength_HT = Avg_home_goals_conceded_by_HT / Avg_conced_Home

        List_off_strength_AT.append(Off_strength_AT)
        List_def_strength_HT.append(Def_strength_HT)

    playing_stat['Off_strength_HT'] = List_off_strength_HT
    playing_stat['Def_strength_HT'] = List_def_strength_HT
    playing_stat['Off_strength_AT'] = List_off_strength_AT
    playing_stat['Def_strength_AT'] = List_def_strength_AT

In [42]:
for season in seasons:
    season = get_off_def_strength(season)

## League position from last season

In European football leauges every season teams (usually 3 but it depends) can get promotion to the highest league and other teams can fall out. This way we get different teams every seasons. So to get league postion from last season I decided to assign to new teams a specific postion:
* number of teams in the highest league + new team's league postion from the second highest league
* for example in 2020/21 season Benevento was new team and they have 1st postion in 2019/20 season in the second highest league so I assign number 21

In [43]:
Standings = pd.read_csv('league_tables/SerieA_table_rank.csv', sep=';') # This table was created manually 
Standings.set_index(['Team'], inplace=True)

In [44]:
# Add variables with last league postion
def get_last(playing_stat, Standings, year):
    HomeTeamLP = []
    AwayTeamLP = []
    for i in range(len(playing_stat)):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HomeTeamLP.append(Standings.loc[ht][year])
        AwayTeamLP.append(Standings.loc[at][year])
    playing_stat['HomeTeamLP'] = HomeTeamLP
    playing_stat['AwayTeamLP'] = AwayTeamLP
    return playing_stat

In [45]:
SerieA_11_12_data = get_last(SerieA_11_12_data, Standings, '2010/11')
SerieA_12_13_data = get_last(SerieA_12_13_data, Standings, '2011/12')
SerieA_13_14_data = get_last(SerieA_13_14_data, Standings, '2012/13')
SerieA_14_15_data = get_last(SerieA_14_15_data, Standings, '2013/14')
SerieA_15_16_data = get_last(SerieA_15_16_data, Standings, '2014/15')
SerieA_16_17_data = get_last(SerieA_16_17_data, Standings, '2015/16')
SerieA_17_18_data = get_last(SerieA_17_18_data, Standings, '2016/17')
SerieA_18_19_data = get_last(SerieA_18_19_data, Standings, '2017/18')
SerieA_19_20_data = get_last(SerieA_19_20_data, Standings, '2018/19')
SerieA_20_21_data = get_last(SerieA_20_21_data, Standings, '2019/20')

In [46]:
# adding binary variable if specific team is a new team in specific season
def get_newTeam(playing_stat):
    
    teams_number = len(playing_stat.HomeTeam.unique())
    
    playing_stat['Is_HT_newTeam'] = [1 if x > teams_number else 0 for x in playing_stat.HomeTeamLP]
    playing_stat['Is_AT_newTeam'] = [1 if x > teams_number else 0 for x in playing_stat.AwayTeamLP]
    
    return playing_stat

In [47]:
# Data was only for the last 10 completed season so I cant use every historical dataset
for season in [ SerieA_11_12_data,
            SerieA_12_13_data, 
            SerieA_13_14_data,
            SerieA_14_15_data, 
            SerieA_15_16_data, 
            SerieA_16_17_data, 
            SerieA_17_18_data, 
            SerieA_18_19_data, 
            SerieA_19_20_data, 
            SerieA_20_21_data]:
    season = get_newTeam(season)

In [48]:
# Checking if everything is correct
for season in [ SerieA_11_12_data,
            SerieA_12_13_data, 
            SerieA_13_14_data,
            SerieA_14_15_data, 
            SerieA_15_16_data, 
            SerieA_16_17_data, 
            SerieA_17_18_data, 
            SerieA_18_19_data, 
            SerieA_19_20_data, 
            SerieA_20_21_data]:
    print(season[season.HomeTeamLP > 20].HomeTeam.unique())

['Atalanta' 'Siena' 'Novara']
['Pescara' 'Torino' 'Sampdoria']
['Verona' 'Livorno' 'Sassuolo']
['Cesena' 'Palermo' 'Empoli']
['Frosinone' 'Bologna' 'Carpi']
['Pescara' 'Cagliari' 'Crotone']
['Verona' 'Benevento' 'Spal']
['Empoli' 'Parma' 'Frosinone']
['Verona' 'Lecce' 'Brescia']
['Spezia' 'Crotone' 'Benevento']

## Team data for every season from transfermarkt
* Average age
* Number of foreigners
* Average market value in milions of Euro
* Total market value in milions of Euro

Example data from 2016/17 season:
https://www.transfermarkt.com/serie-a/startseite/wettbewerb/IT1/plus/?saison_id=2016

In [49]:
SerieA_budget = pd.read_csv("budget_data/SerieA_transfermaket_data.csv", sep=';')
SerieA_budget.set_index(['Club'], inplace=True)
SerieA_budget

,Avg_age,Foreigners,Avg_market_value_MLN_EUR,Total_market_value_MLN_EUR,Season
Club,,,,,
Inter,"25,4",28,"6,31","303,05",2011/12
Milan,"26,2",21,"6,08","273,53",2011/12
Juventus,"27,8",12,"7,71","262,28",2011/12
Napoli,"28,2",15,"7,06","204,75",2011/12
Roma,"25,5",18,"4,43","172,78",2011/12
...,...,...,...,...,...
Sampdoria,"26,4",17,"3,74","127,18",2020/21
Genoa,"26,5",23,"2,54","111,93",2020/21
Spezia,"25,7",17,"1,84","71,68",2020/21
Crotone,26,19,"1,29","52,75",2020/21
Benevento,"27,4",14,"1,39","50,13",2020/21

Changing string variables for float

In [50]:
SerieA_budget['Avg_age'].replace(',', '.', regex=True, inplace=True)
SerieA_budget['Avg_market_value_MLN_EUR'].replace(',', '.', regex=True, inplace=True)
SerieA_budget['Total_market_value_MLN_EUR'].replace(',', '.', regex=True, inplace=True)

In [51]:
SerieA_budget.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, Inter to Benevento
Data columns (total 5 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Avg_age                     200 non-null    object
 1   Foreigners                  200 non-null    int64
 2   Avg_market_value_MLN_EUR    200 non-null    object
 3   Total_market_value_MLN_EUR  200 non-null    object
 4   Season                      200 non-null    object
dtypes: int64(1), object(4)
memory usage: 9.4+ KB

In [52]:
SerieA_budget.Avg_age = SerieA_budget.Avg_age.astype(float)
SerieA_budget.Avg_market_value_MLN_EUR = SerieA_budget.Avg_market_value_MLN_EUR.astype(float)
SerieA_budget.Total_market_value_MLN_EUR = SerieA_budget.Total_market_value_MLN_EUR.astype(float)

In [53]:
# function summarizing and adding variables
def get_transfermarkt_data(season_data, Budget):
    
    HomeTeam_TM_avg_age = []
    HomeTeam_TM_foreigners_number = []
    HomeTeam_TM_avg_market_value_MLN_EUR = []
    HomeTeam_TM_total_market_value_MLN_EUR = []
    
    AwayTeam_TM_avg_age = []
    AwayTeam_TM_foreigners_number = []
    AwayTeam_TM_avg_market_value_MLN_EUR = []
    AwayTeam_TM_total_market_value_MLN_EUR = []
    
    for season in list(season_data.Season.unique()):
        
        SerieA_budget_season = Budget[Budget.Season == season]
        
        for i in range(len(season_data)):
            
            home_team = season_data[season_data.Season == season].iloc[i].HomeTeam
            away_team = season_data[season_data.Season == season].iloc[i].AwayTeam
            
            HomeTeam_TM_avg_age.append(SerieA_budget_season.loc[home_team]['Avg_age'])
            HomeTeam_TM_foreigners_number.append(SerieA_budget_season.loc[home_team]['Foreigners'])
            HomeTeam_TM_avg_market_value_MLN_EUR.append(SerieA_budget_season.loc[home_team]['Avg_market_value_MLN_EUR'])
            HomeTeam_TM_total_market_value_MLN_EUR.append(SerieA_budget_season.loc[home_team]['Total_market_value_MLN_EUR'])
            
            AwayTeam_TM_avg_age.append(SerieA_budget_season.loc[away_team]['Avg_age'])
            AwayTeam_TM_foreigners_number.append(SerieA_budget_season.loc[away_team]['Foreigners'])
            AwayTeam_TM_avg_market_value_MLN_EUR.append(SerieA_budget_season.loc[away_team]['Avg_market_value_MLN_EUR'])
            AwayTeam_TM_total_market_value_MLN_EUR.append(SerieA_budget_season.loc[away_team]['Total_market_value_MLN_EUR'])
            
            
    season_data['HomeTeam_TM_avg_age'] = HomeTeam_TM_avg_age
    season_data['HomeTeam_TM_foreigners_number'] = HomeTeam_TM_foreigners_number
    season_data['HomeTeam_TM_avg_market_value_MLN_EUR'] = HomeTeam_TM_avg_market_value_MLN_EUR
    season_data['HomeTeam_TM_total_market_value_MLN_EUR'] = HomeTeam_TM_total_market_value_MLN_EUR
    
    season_data['AwayTeam_TM_avg_age'] = AwayTeam_TM_avg_age
    season_data['AwayTeam_TM_foreigners_number'] = AwayTeam_TM_foreigners_number
    season_data['AwayTeam_TM_avg_market_value_MLN_EUR'] = AwayTeam_TM_avg_market_value_MLN_EUR
    season_data['AwayTeam_TM_total_market_value_MLN_EUR'] = AwayTeam_TM_total_market_value_MLN_EUR
    
    return season_data

In [54]:
for season in [SerieA_11_12_data, SerieA_12_13_data, SerieA_13_14_data, SerieA_14_15_data, SerieA_15_16_data, 
              SerieA_16_17_data, SerieA_17_18_data, SerieA_18_19_data, SerieA_19_20_data, SerieA_20_21_data]:
    
    get_transfermarkt_data(season, SerieA_budget)

## Data concatenating

In [55]:
SerieA_data = pd.concat([SerieA_00_01_data, 
                      SerieA_01_02_data, 
                      SerieA_02_03_data, 
                      SerieA_03_04_data, 
                      SerieA_04_05_data, 
                      SerieA_05_06_data, 
                      SerieA_06_07_data, 
                      SerieA_07_08_data, 
                      SerieA_08_09_data, 
                      SerieA_09_10_data, 
                      SerieA_10_11_data, 
                      SerieA_11_12_data,
                      SerieA_12_13_data, 
                      SerieA_13_14_data,
                      SerieA_14_15_data, 
                      SerieA_15_16_data, 
                      SerieA_16_17_data, 
                      SerieA_17_18_data, 
                      SerieA_18_19_data, 
                      SerieA_19_20_data, 
                      SerieA_20_21_data], ignore_index=True)

In [56]:
# deleting unnecessary data
del SerieA_00_01_data, SerieA_01_02_data, SerieA_02_03_data, SerieA_03_04_data, SerieA_04_05_data, SerieA_05_06_data
del SerieA_06_07_data, SerieA_07_08_data, SerieA_08_09_data, SerieA_09_10_data
del SerieA_20_21_data_all_col
del season, seasons

## Calcuating betting odds
* 1x (Home win or Draw) = 100 / (100/Home_win_odds + 100/Draw_odds)
* x2 (Away win or Draw) = 100 / (100/Away_win_odds + 100/Draw_odds)

In [57]:
def get_more_odds(playing_stat):
    x1 = []
    x2 = []
    
    for i, row in playing_stat.iterrows():
        b365_H = playing_stat.iloc[i]['B365H']
        b365_D = playing_stat.iloc[i]['B365D']
        b365_A = playing_stat.iloc[i]['B365A']
        
        odd_H = 100/b365_H
        odd_D = 100/b365_D
        odd_A = 100/b365_A
        
        b365_H_D = round((100/(odd_H + odd_D)), 2)
        b365_A_D = round((100/(odd_A + odd_D)), 2)
        
        x1.append(b365_H_D)
        x2.append(b365_A_D)
        
    
    playing_stat['B365_HD'] = x1
    playing_stat['B365_AD'] = x2
    
    return playing_stat

In [58]:
get_more_odds(SerieA_data)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,Season,HT_last_matches_number,AT_last_matches_number,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HT_cum_wins,AT_cum_wins,HT_cum_losses,AT_cum_losses,HT_cum_draws,AT_cum_draws,Off_strength_HT,Def_strength_HT,Off_strength_AT,Def_strength_AT,HS,AS,HST,AST,B365H,B365D,B365A,HTSOT_T,ATSOT_T,HTSOT_A,ATSOT_A,HT_Shot_Acc,AT_Shot_Acc,HT_Op_Shot_Acc,AT_Op_Shot_Acc,HomeTeamLP,AwayTeamLP,Is_HT_newTeam,Is_AT_newTeam,HomeTeam_TM_avg_age,HomeTeam_TM_foreigners_number,HomeTeam_TM_avg_market_value_MLN_EUR,HomeTeam_TM_total_market_value_MLN_EUR,AwayTeam_TM_avg_age,AwayTeam_TM_foreigners_number,AwayTeam_TM_avg_market_value_MLN_EUR,AwayTeam_TM_total_market_value_MLN_EUR,B365_HD,B365_AD
0,I1,2000-09-30,Bari,Verona,1.0,1.0,D,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I1,2000-09-30,Napoli,Juventus,1.0,2.0,A,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I1,2000-10-01,Atalanta,Lazio,2.0,2.0,D,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I1,2000-10-01,Milan,Vicenza,2.0,0.0,H,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,I1,2000-10-01,Parma,Fiorentina,2.0,2.0,D,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7679,I1,2021-05-23,Bologna,Juventus,1.0,4.0,A,2020/21,37,37,50.0,73.0,61.0,37.0,41,75,D,W,L,W,D,L,D,W,L,D,10,22,16,6,11,9,1.094243,1.131722,1.287822,0.649707,18.0,19.0,5.0,11.0,10.50,7.00,1.22,210.0,243.0,238.0,143.0,0.238095,0.300412,0.256303,0.258741,12.0,1.0,0.0,0.0,24.1,27.0,3.41,153.60,24.7,26.0,14.07,633.30,4.20,1.04
7680,I1,2021-05-23,Napoli,Verona,1.0,1.0,D,2020/21,37,37,85.0,42.0,40.0,47.0,76,42,W,D,W,L,W,D,D,D,W,L,24,10,9,15,4,12,1.675559,0.741473,0.858548,0.820682,16.0,7.0,3.0,4.0,1.18,7.50,13.00,277.0,164.0,146.0,179.0,0.306859,0.256098,0.273973,0.262570,7.0,9.0,0.0,0.0,26.0,21.0,16.57,530.20,24.2,20.0,3.42,157.21,1.02,4.76
7681,I1,2021-05-23,Sassuolo,Lazio,2.0,0.0,H,2020/21,37,37,62.0,61.0,56.0,53.0,59,68,W,D,L,L,W,W,D,L,W,W,16,21,10,11,11,5,0.991657,1.053672,0.975623,1.025853,10.0,9.0,5.0,2.0,1.90,4.33,3.25,212.0,223.0,238.0,177.0,0.292453,0.273543,0.235294,0.299435,8.0,4.0,0.0,0.0,24.9,18.0,6.20,241.74,25.6,32.0,7.42,326.33,1.32,1.86
7682,I1,2021-05-23,Spezia,Roma,2.0,2.0,D,2020/21,37,37,50.0,66.0,70.0,53.0,38,62,W,W,D,L,L,W,D,L,L,L,9,18,17,11,11,8,0.889072,1.209772,0.936598,1.196828,18.0,14.0,9.0,10.0,5.00,4.60,1.57,162.0,238.0,199.0,187.0,0.308642,0.277311,0.351759,0.283422,23.0,5.0,1.0,0.0,25.7,17.0,1.84,71.68,24.6,28.0,8.60,395.65,2.40,1.17
7683,I1,2021-05-23,Torino,Benevento,1.0,1.0,D,2020/21,37,37,49.0,39.0,68.0,74.0,36,32,D,D,L,L,L,L,D,L,W,L,7,7,15,19,15,11,0.820682,1.365872,0.780498,1.196828,12.0,9.0,7.0,3.0,1.75,4.33,3.90,195.0,161.0,208.0,219.0,0.251282,0.242236,0.326923,0.337900,16.0,21.0,0.0,1.0,25.4,22.0,4.38,175.28,27.4,14.0,1.39,50.13,1.25,2.05

## Add points collect by teams from last 3 and 5 games

In [59]:
# Gets the form points.
def get_form_points(string):
    sum = 0
    for letter in string:
        sum += get_points(letter) # using other function
    return sum

In [60]:
# Concatenate variables with last team's results
SerieA_data['HT_3match_FormPtsStr'] = SerieA_data['HM1'] + SerieA_data['HM2'] + SerieA_data['HM3']
SerieA_data['AT_3match_FormPtsStr'] = SerieA_data['AM1'] + SerieA_data['AM2'] + SerieA_data['AM3']

SerieA_data['HT_5match_FormPtsStr'] = SerieA_data['HM1'] + SerieA_data['HM2'] + SerieA_data['HM3'] + SerieA_data['HM4'] + SerieA_data['HM5']
SerieA_data['AT_5match_FormPtsStr'] = SerieA_data['AM1'] + SerieA_data['AM2'] + SerieA_data['AM3'] + SerieA_data['AM4'] + SerieA_data['AM5']

# Applying function to get points
SerieA_data['HT_3match_FormPts'] = SerieA_data['HT_3match_FormPtsStr'].apply(get_form_points)
SerieA_data['AT_3match_FormPts'] = SerieA_data['AT_3match_FormPtsStr'].apply(get_form_points)

SerieA_data['HT_5match_FormPts'] = SerieA_data['HT_5match_FormPtsStr'].apply(get_form_points)
SerieA_data['AT_5match_FormPts'] = SerieA_data['AT_5match_FormPtsStr'].apply(get_form_points)

## Win or loss streaks

In [61]:
# Identify Win/Loss Streaks if any.
def get_3game_ws(string):
    if string == 'WWW':
        return 1
    else:
        return 0
    
def get_5game_ws(string):
    if string == 'WWWWW':
        return 1
    else:
        return 0
    
def get_3game_ls(string):
    if string == 'LLL':
        return 1
    else:
        return 0
    
def get_5game_ls(string):
    if string == 'LLLLL':
        return 1
    else:
        return 0

In [62]:
SerieA_data['HTWinStreak3'] = SerieA_data['HT_3match_FormPtsStr'].apply(get_3game_ws)
SerieA_data['HTWinStreak5'] = SerieA_data['HT_5match_FormPtsStr'].apply(get_5game_ws)
SerieA_data['HTLossStreak3'] = SerieA_data['HT_3match_FormPtsStr'].apply(get_3game_ls)
SerieA_data['HTLossStreak5'] = SerieA_data['HT_5match_FormPtsStr'].apply(get_5game_ls)

SerieA_data['ATWinStreak3'] = SerieA_data['AT_3match_FormPtsStr'].apply(get_3game_ws)
SerieA_data['ATWinStreak5'] = SerieA_data['AT_5match_FormPtsStr'].apply(get_5game_ws)
SerieA_data['ATLossStreak3'] = SerieA_data['AT_3match_FormPtsStr'].apply(get_3game_ls)
SerieA_data['ATLossStreak5'] = SerieA_data['AT_5match_FormPtsStr'].apply(get_5game_ls)

## Head to Head (H2H) variables
* Getting last 3 head to head match results and change it for points

In [63]:
def h2h(playing_stat):
    
    playing_stat["H2H_Home"] = ""
    playing_stat["H2H_Away"] = ""

    for i in range(1,len(playing_stat)):
        # get teams from specifc match and all data before this match
        df = playing_stat.iloc[0:i-1,]
        ht = playing_stat.loc[i,"HomeTeam"]
        at = playing_stat.loc[i,"AwayTeam"]
        
        # getting last 3 head to head matches
        dff = df[(((df.HomeTeam == ht) &  (df.AwayTeam == at)) | ((df.HomeTeam == at) &  (df.AwayTeam == ht)))].tail(3)
        
        # using data with minimum 1 head to head match
        if (len(dff) >= 1):
            for j in range(0,len(dff)):
                # Consider all possible scenarios
                if ((dff.iloc[j].HomeTeam == ht)  and (dff.iloc[j]["FTR"] == "H")):
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] += "W"
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] += "L"
                elif ((dff.iloc[j].HomeTeam == at)  and (dff.iloc[j]["FTR"] == "H")):
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] += "L"
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] += "W"
                elif ((dff.iloc[j].HomeTeam == ht)  and (dff.iloc[j]["FTR"] == "A")):
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] += "L"
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] += "W"
                elif ((dff.iloc[j].HomeTeam == at)  and (dff.iloc[j]["FTR"] == "A")):
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] += "W"
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] += "L"
                elif ((dff.iloc[j].HomeTeam == ht)  and (dff.iloc[j]["FTR"] == "D")):
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] += "D"
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] += "D"
                elif ((dff.iloc[j].HomeTeam == at)  and (dff.iloc[j]["FTR"] == "D")):
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] += "D"
                    playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] += "D"
                    
        # if there was no match beetwen the teams get 'ND'
        else: 
            playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Home')] = "ND"
            playing_stat.iloc[i, playing_stat.columns.get_loc('H2H_Away')] = "ND"
    return playing_stat


# Calculating points for Home and Away teams in head to head matches and adding variables
def get_points_h2h(playing_stat, col):
    
    playing_stat[col+"_pts"] = 0
    
    for i in range(1,len(playing_stat)):
        if (len(playing_stat.iloc[i][col]) == 1):
            if playing_stat.iloc[i][col][0] =='L':
                playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] += 0
            elif playing_stat.iloc[i][col][0] =='W':
                playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] +=  3
            else:
                playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] +=  1
        elif (len(playing_stat.iloc[i][col]) == 2):
            for j in range(0,2):
                if playing_stat.iloc[i][col][j] =='L':
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] += 0
                elif playing_stat.iloc[i][col][j] =='W':
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] +=  3
                elif playing_stat.iloc[i][col][j] =='D':
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] +=  1
                else:
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] += 0
        elif (len(playing_stat.iloc[i][col]) == 3):
            for j in range(0,3):
                if playing_stat.iloc[i][col][j] =='L':
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] += 0
                elif playing_stat.iloc[i][col][j] =='W':
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] +=  3
                elif playing_stat.iloc[i][col][j] =='D':
                    playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] +=  1
        else:
            playing_stat.iloc[i, playing_stat.columns.get_loc(col+"_pts")] = 0
    
    return playing_stat

In [64]:
h2h(SerieA_data)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,Season,HT_last_matches_number,AT_last_matches_number,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HT_cum_wins,AT_cum_wins,HT_cum_losses,AT_cum_losses,HT_cum_draws,AT_cum_draws,Off_strength_HT,Def_strength_HT,Off_strength_AT,Def_strength_AT,HS,AS,HST,AST,B365H,B365D,B365A,HTSOT_T,ATSOT_T,HTSOT_A,ATSOT_A,HT_Shot_Acc,AT_Shot_Acc,HT_Op_Shot_Acc,AT_Op_Shot_Acc,HomeTeamLP,AwayTeamLP,Is_HT_newTeam,Is_AT_newTeam,HomeTeam_TM_avg_age,HomeTeam_TM_foreigners_number,HomeTeam_TM_avg_market_value_MLN_EUR,HomeTeam_TM_total_market_value_MLN_EUR,AwayTeam_TM_avg_age,AwayTeam_TM_foreigners_number,AwayTeam_TM_avg_market_value_MLN_EUR,AwayTeam_TM_total_market_value_MLN_EUR,B365_HD,B365_AD,HT_3match_FormPtsStr,AT_3match_FormPtsStr,HT_5match_FormPtsStr,AT_5match_FormPtsStr,HT_3match_FormPts,AT_3match_FormPts,HT_5match_FormPts,AT_5match_FormPts,HTWinStreak3,HTWinStreak5,HTLossStreak3,HTLossStreak5,ATWinStreak3,ATWinStreak5,ATLossStreak3,ATLossStreak5,H2H_Home,H2H_Away
0,I1,2000-09-30,Bari,Verona,1.0,1.0,D,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NDNDND,NDNDND,NDNDNDNDND,NDNDNDNDND,3,3,5,5,0,0,0,0,0,0,0,0,,
1,I1,2000-09-30,Napoli,Juventus,1.0,2.0,A,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NDNDND,NDNDND,NDNDNDNDND,NDNDNDNDND,3,3,5,5,0,0,0,0,0,0,0,0,ND,ND
2,I1,2000-10-01,Atalanta,Lazio,2.0,2.0,D,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NDNDND,NDNDND,NDNDNDNDND,NDNDNDNDND,3,3,5,5,0,0,0,0,0,0,0,0,ND,ND
3,I1,2000-10-01,Milan,Vicenza,2.0,0.0,H,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NDNDND,NDNDND,NDNDNDNDND,NDNDNDNDND,3,3,5,5,0,0,0,0,0,0,0,0,ND,ND
4,I1,2000-10-01,Parma,Fiorentina,2.0,2.0,D,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NDNDND,NDNDND,NDNDNDNDND,NDNDNDNDND,3,3,5,5,0,0,0,0,0,0,0,0,ND,ND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7679,I1,2021-05-23,Bologna,Juventus,1.0,4.0,A,2020/21,37,37,50.0,73.0,61.0,37.0,41,75,D,W,L,W,D,L,D,W,L,D,10,22,16,6,11,9,1.094243,1.131722,1.287822,0.649707,18.0,19.0,5.0,11.0,10.50,7.00,1.22,210.0,243.0,238.0,143.0,0.238095,0.300412,0.256303,0.258741,12.0,1.0,0.0,0.0,24.1,27.0,3.41,153.60,24.7,26.0,14.07,633.30,4.20,1.04,DLD,WWL,DLDDL,WWLWD,2,6,3,10,0,0,0,0,0,0,0,0,LLL,WWW
7680,I1,2021-05-23,Napoli,Verona,1.0,1.0,D,2020/21,37,37,85.0,42.0,40.0,47.0,76,42,W,D,W,L,W,D,D,D,W,L,24,10,9,15,4,12,1.675559,0.741473,0.858548,0.820682,16.0,7.0,3.0,4.0,1.18,7.50,13.00,277.0,164.0,146.0,179.0,0.306859,0.256098,0.273973,0.262570,7.0,9.0,0.0,0.0,26.0,21.0,16.57,530.20,24.2,20.0,3.42,157.21,1.02,4.76,WWW,DLD,WWWDW,DLDDL,9,2,13,3,1,0,0,0,0,0,0,0,WWL,LLW
7681,I1,2021-05-23,Sassuolo,Lazio,2.0,0.0,H,2020/21,37,37,62.0,61.0,56.0,53.0,59,68,W,D,L,L,W,W,D,L,W,W,16,21,10,11,11,5,0.991657,1.053672,0.975623,1.025853,10.0,9.0,5.0,2.0,1.90,4.33,3.25,212.0,223.0,238.0,177.0,0.292453,0.273543,0.235294,0.299435,8.0,4.0,0.0,0.0,24.9,18.0,6.20,241.74,25.6,32.0,7.42,326.33,1.32,1.86,WLW,DLW,WLWDW,DLWLW,6,4,10,7,0,0,0,0,0,0,0,0,LWL,WLW
7682,I1,2021-05-23,Spezia,Roma,2.0,2.0,D,2020/21,37,37,50.0,66.0,70.0,53.0,38,62,W,W,D,L,L,W,D,L,L,L,9,18,17,11,11,8,0.889072,1.209772,0.936598,1.196828,18.0,14.0,9.0,10.0,5.00,4.60,1.57,162.0,238.0,199.0,187.0,0.308642,0.277311,0.351759,0.283422,23.0,5.0,1.0,0.0,25.7,17.0,1.84,71.68,24.6,28.0,8.60,395.65,2.40,1.17,WDL,WLW,WDLDL,WLWLL,4,6,5,6,0,0,0,0,0,0,0,0,L,W
7683,I1,2021-05-23,Torino,Benevento,1.0,1.0,D,2020/21,37,37,49.0,39.0,68.0,74.0,36,32,D,D,L,L,L,L,D,L,W,L,7,7,15,19,15,11,0.820682,1.365872,0.780498,1.196828,12.0,9.0,7.0,3.0,1.75,4.33,3.90,195.0,161.0,208.0,219.0,0.251282,0.242236,0.326923,0.337900,16.0,21.0,0.0,1.0,25.4,22.0,4.38,175.28,27.4,14.0,1.39,50.13,1.25,2.05,DLL,DLL,DLLDW,DLLLL,1,1,5,1,0,0,0,0,0,0,0,0,WWD,LLD

In [65]:
get_points_h2h(SerieA_data, "H2H_Home") 
get_points_h2h(SerieA_data, "H2H_Away")

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,Season,HT_last_matches_number,AT_last_matches_number,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HT_cum_wins,AT_cum_wins,HT_cum_losses,AT_cum_losses,HT_cum_draws,AT_cum_draws,Off_strength_HT,Def_strength_HT,Off_strength_AT,Def_strength_AT,HS,AS,HST,AST,B365H,B365D,B365A,HTSOT_T,ATSOT_T,HTSOT_A,ATSOT_A,HT_Shot_Acc,AT_Shot_Acc,HT_Op_Shot_Acc,AT_Op_Shot_Acc,HomeTeamLP,AwayTeamLP,Is_HT_newTeam,Is_AT_newTeam,HomeTeam_TM_avg_age,HomeTeam_TM_foreigners_number,HomeTeam_TM_avg_market_value_MLN_EUR,HomeTeam_TM_total_market_value_MLN_EUR,AwayTeam_TM_avg_age,AwayTeam_TM_foreigners_number,AwayTeam_TM_avg_market_value_MLN_EUR,AwayTeam_TM_total_market_value_MLN_EUR,B365_HD,B365_AD,HT_3match_FormPtsStr,AT_3match_FormPtsStr,HT_5match_FormPtsStr,AT_5match_FormPtsStr,HT_3match_FormPts,AT_3match_FormPts,HT_5match_FormPts,AT_5match_FormPts,HTWinStreak3,HTWinStreak5,HTLossStreak3,HTLossStreak5,ATWinStreak3,ATWinStreak5,ATLossStreak3,ATLossStreak5,H2H_Home,H2H_Away,H2H_Home_pts,H2H_Away_pts
0,I1,2000-09-30,Bari,Verona,1.0,1.0,D,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NDNDND,NDNDND,NDNDNDNDND,NDNDNDNDND,3,3,5,5,0,0,0,0,0,0,0,0,,,0,0
1,I1,2000-09-30,Napoli,Juventus,1.0,2.0,A,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NDNDND,NDNDND,NDNDNDNDND,NDNDNDNDND,3,3,5,5,0,0,0,0,0,0,0,0,ND,ND,1,1
2,I1,2000-10-01,Atalanta,Lazio,2.0,2.0,D,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NDNDND,NDNDND,NDNDNDNDND,NDNDNDNDND,3,3,5,5,0,0,0,0,0,0,0,0,ND,ND,1,1
3,I1,2000-10-01,Milan,Vicenza,2.0,0.0,H,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NDNDND,NDNDND,NDNDNDNDND,NDNDNDNDND,3,3,5,5,0,0,0,0,0,0,0,0,ND,ND,1,1
4,I1,2000-10-01,Parma,Fiorentina,2.0,2.0,D,2000/01,0,0,0.0,0.0,0.0,0.0,0,0,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NDNDND,NDNDND,NDNDNDNDND,NDNDNDNDND,3,3,5,5,0,0,0,0,0,0,0,0,ND,ND,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7679,I1,2021-05-23,Bologna,Juventus,1.0,4.0,A,2020/21,37,37,50.0,73.0,61.0,37.0,41,75,D,W,L,W,D,L,D,W,L,D,10,22,16,6,11,9,1.094243,1.131722,1.287822,0.649707,18.0,19.0,5.0,11.0,10.50,7.00,1.22,210.0,243.0,238.0,143.0,0.238095,0.300412,0.256303,0.258741,12.0,1.0,0.0,0.0,24.1,27.0,3.41,153.60,24.7,26.0,14.07,633.30,4.20,1.04,DLD,WWL,DLDDL,WWLWD,2,6,3,10,0,0,0,0,0,0,0,0,LLL,WWW,0,9
7680,I1,2021-05-23,Napoli,Verona,1.0,1.0,D,2020/21,37,37,85.0,42.0,40.0,47.0,76,42,W,D,W,L,W,D,D,D,W,L,24,10,9,15,4,12,1.675559,0.741473,0.858548,0.820682,16.0,7.0,3.0,4.0,1.18,7.50,13.00,277.0,164.0,146.0,179.0,0.306859,0.256098,0.273973,0.262570,7.0,9.0,0.0,0.0,26.0,21.0,16.57,530.20,24.2,20.0,3.42,157.21,1.02,4.76,WWW,DLD,WWWDW,DLDDL,9,2,13,3,1,0,0,0,0,0,0,0,WWL,LLW,6,3
7681,I1,2021-05-23,Sassuolo,Lazio,2.0,0.0,H,2020/21,37,37,62.0,61.0,56.0,53.0,59,68,W,D,L,L,W,W,D,L,W,W,16,21,10,11,11,5,0.991657,1.053672,0.975623,1.025853,10.0,9.0,5.0,2.0,1.90,4.33,3.25,212.0,223.0,238.0,177.0,0.292453,0.273543,0.235294,0.299435,8.0,4.0,0.0,0.0,24.9,18.0,6.20,241.74,25.6,32.0,7.42,326.33,1.32,1.86,WLW,DLW,WLWDW,DLWLW,6,4,10,7,0,0,0,0,0,0,0,0,LWL,WLW,3,6
7682,I1,2021-05-23,Spezia,Roma,2.0,2.0,D,2020/21,37,37,50.0,66.0,70.0,53.0,38,62,W,W,D,L,L,W,D,L,L,L,9,18,17,11,11,8,0.889072,1.209772,0.936598,1.196828,18.0,14.0,9.0,10.0,5.00,4.60,1.57,162.0,238.0,199.0,187.0,0.308642,0.277311,0.351759,0.283422,23.0,5.0,1.0,0.0,25.7,17.0,1.84,71.68,24.6,28.0,8.60,395.65,2.40,1.17,WDL,WLW,WDLDL,WLWLL,4,6,5,6,0,0,0,0,0,0,0,0,L,W,0,3
7683,I1,2021-05-23,Torino,Benevento,1.0,1.0,D,2020/21,37,37,49.0,39.0,68.0,74.0,36,32,D,D,L,L,L,L,D,L,W,L,7,7,15,19,15,11,0.820682,1.365872,0.780498,1.196828,12.0,9.0,7.0,3.0,1.75,4.33,3.90,195.0,161.0,208.0,219.0,0.251282,0.242236,0.326923,0.337900,16.0,21.0,0.0,1.0,25.4,22.0,4.38,175.28,27.4,14.0,1.39,50.13,1.25,2.05,DLL,DLL,DLLDW,DLLLL,1,1,5,1,0,0,0,0,0,0,0,0,WWD,LLD,7,1

## Choose last 10 completed seasons

In [66]:
SerieA_data = SerieA_data[SerieA_data.Season.isin(['2011/12', 
                                         '2012/13', 
                                         '2013/14', 
                                         '2014/15', 
                                         '2015/16', 
                                         '2016/17', 
                                         '2017/18', 
                                         '2018/19', 
                                         '2019/20', 
                                         '2020/21'])]

In [67]:
SerieA_data.reset_index(drop=True, inplace=True)
SerieA_data.shape

(3800, 85)

## Correct positioning of the columns and changing col names

In [68]:
SerieA_data_final = SerieA_data[[
    'Div', 'Season', 'Date', 'HomeTeam', 'AwayTeam','FTHG', 'FTAG', 'FTR', 'HS','AS', 'HST', 'AST',
    'HT_last_matches_number', 'AT_last_matches_number', 'B365H', 'B365D', 'B365A', 'B365_HD', 'B365_AD',
    'HTGS', 'ATGS', 'HTGC', 'ATGC',
    'HTSOT_T','ATSOT_T', 'HTSOT_A', 'ATSOT_A', 
    'HT_Shot_Acc', 'AT_Shot_Acc','HT_Op_Shot_Acc', 'AT_Op_Shot_Acc',
    'HTP', 'ATP',
    'HT_cum_wins', 'AT_cum_wins', 'HT_cum_losses', 'AT_cum_losses', 'HT_cum_draws', 'AT_cum_draws',
    'Off_strength_HT', 'Def_strength_HT', 'Off_strength_AT', 'Def_strength_AT',
    'HM1', 'AM1', 'HM2', 'AM2', 'HM3', 'AM3', 'HM4', 'AM4', 'HM5', 'AM5',
    'HT_3match_FormPtsStr', 'AT_3match_FormPtsStr', 'HT_5match_FormPtsStr','AT_5match_FormPtsStr', 
    'HT_3match_FormPts', 'AT_3match_FormPts', 'HT_5match_FormPts', 'AT_5match_FormPts',
    'HTWinStreak3','HTWinStreak5', 'HTLossStreak3', 'HTLossStreak5', 
    'ATWinStreak3','ATWinStreak5', 'ATLossStreak3', 'ATLossStreak5',
    'HomeTeamLP', 'AwayTeamLP', 
    'Is_HT_newTeam', 'Is_AT_newTeam',
    'H2H_Home', 'H2H_Away', 'H2H_Home_pts','H2H_Away_pts',
    'HomeTeam_TM_avg_age','HomeTeam_TM_foreigners_number', 
    'HomeTeam_TM_avg_market_value_MLN_EUR','HomeTeam_TM_total_market_value_MLN_EUR',
    'AwayTeam_TM_avg_age', 'AwayTeam_TM_foreigners_number', 
    'AwayTeam_TM_avg_market_value_MLN_EUR', 'AwayTeam_TM_total_market_value_MLN_EUR'
                          ]]

In [69]:
SerieA_data_final.rename(columns={'HM1': 'HT_last_match1', 'AM1': 'AT_last_match1', 
                               'HM2': 'HT_last_match2', 'AM2': 'AT_last_match2', 
                               'HM3': 'HT_last_match3', 'AM3': 'AT_last_match3', 
                               'HM4': 'HT_last_match4', 'AM4': 'AT_last_match4', 
                               'HM5': 'HT_last_match5', 'AM5': 'AT_last_match5', 
                               'HomeTeamLP': 'HT_last_LP', 'AwayTeamLP': 'AT_last_LP', 
                               #'HTGD': 'HT_goal_diff', 'ATGD': 'AT_goal_diff', 
                               #'DiffLP': 'Diff_last_LP',
                               'HTP': 'HT_Pts', 'ATP': 'AT_Pts', 
                               'HTSOT_T': 'HT_Shots_OT_took','ATSOT_T': 'AT_Shots_OT_took', 
                               'HTSOT_A': 'HT_Shots_OT_allowed','ATSOT_A': 'AT_Shots_OT_allowed', 
                               'HT_Shot_Acc': 'HT_Shots_took_Acc', 'AT_Shot_Acc': 'AT_Shots_took_Acc',
                               'HT_Op_Shot_Acc': 'HT_Shots_allowed_Acc', 'AT_Op_Shot_Acc': 'AT_Shots_allowed_Acc'
                              }, inplace=True)

## Save created dataset

In [70]:
SerieA_data_final.to_csv(path_or_buf= 'Final_data/SerieA_data_final.csv', index=False)